In [3]:
import chemfp
# from chemfp.bitops import 
import pandas as pd
from rdkit.Chem import PandasTools, Draw
from rdkit import DataStructs
from rdkit.ML.Cluster import Butina
from rdkit.Chem import rdMolDescriptors as rdmd
from rdkit.Chem import Descriptors
import seaborn as sns
from IPython.display import HTML
from tqdm import tqdm
from sklearn.metrics import adjusted_rand_score as ari
from sklearn.metrics import silhouette_scorepKi_threshold = 4

In [2]:
def butina_cluster(mol_list,cutoff=0.35):
    fp_list = [rdmd.GetMorganFingerprintAsBitVect(m, 2, nBits=1024) for m in mol_list]
    dists = []
    nfps = len(fp_list)
    for i in tqdm(range(1, nfps)):
        sims = DataStructs.BulkTanimotoSimilarity(fp_list[i],fp_list[:i])
        dists.extend([1-x for x in sims])
    mol_clusters = Butina.ClusterData(dists,nfps,cutoff,isDistData=True)
    cluster_id_list = [0]*nfps
    print(len(cluster_id_list))
    for idx,cluster in enumerate(mol_clusters,1):
        for member in cluster:
            cluster_id_list[member] = idx
    return cluster_id_list, mol_clusters

In [3]:
df = pd.read_csv("BL_Sets_data_rdkitblog.csv", sep=",")
df = df[df["pKi"]>pKi_threshold]
PandasTools.AddMoleculeColumnToFrame(df,smilesCol="smiles")
from time import time
st = time()
y = butina_cluster(df.ROMol.values)
print("Time: ", time()-st)

100%|██████████| 91662/91662 [17:28<00:00, 87.46it/s]  


Time:  1856.2847983837128


In [52]:
data.shape

(91662, 1024)

In [1]:
import numpy as np
import pandas as pd
from rdkit import Chem, DataStructs
from rdkit.Chem import rdFingerprintGenerator
from classix_m import CLASSIX_M
from classix_t import CLASSIX_T
# Setting up the Hyperparameters

regenerateFromScratch = False   # generate Morgan Fingerprints can take a while, so we save
pKi_threshold = 4
tanimoto_radius = 0.33
manhattan_radius = 1.3
mergeScale = 1.33
minPts = 50

# Loading the Data
if regenerateFromScratch:
    # Data should be generated from scratch if the pKi threshold is changed.
    
    fp_gen = rdFingerprintGenerator.GetMorganGenerator(
        radius=2,  # atom radius to consider for hashing
        fpSize=1024  # bit-length of vector (smaller will lead to more collissions during hashing) 
    )
    df = pd.read_csv("BL_Sets_data_rdkitblog.csv", sep=",")
    df["mol"] = df["smiles"].apply(Chem.MolFromSmiles)
    df = df[df["pKi"]>pKi_threshold]
    data = np.vstack(df["mol"].apply(fp_gen.GetFingerprintAsNumPy))
    np.save('BL_Sets.npy', data, allow_pickle=True)
else:
    df = pd.read_csv("BL_Sets_data_rdkitblog.csv", sep=",")
    df = df[df["pKi"]>pKi_threshold]
    data = np.load('BL_Sets.npy')

cluster_membership = df["target_chembl_id"].astype("category").cat.codes
true_labels = np.array(cluster_membership)

# Initialise the models
clx_t = CLASSIX_T(radius=tanimoto_radius, minPts=minPts, mergeScale=mergeScale)
clx_m = CLASSIX_M(radius=1, minPts=100, mergeScale=1.3)

data = data.astype(np.int32)
# clx_m.fit(data)
# Run Tanimoto Clustering
clx_t.fit(data, r=tanimoto_radius, mergeScale=mergeScale)


OWN AGGREGATION


100%|██████████| 90498/90498 [00:42<00:00, 2136.06it/s] 


time for ips: 34.10639977455139
time for search: 1.7810029983520508
time for conversion: 2.0306832790374756
time for loop: 3.7348947525024414
nr_dist: 588244445


  0%|          | 0/16385 [00:00<?, ?it/s]

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18 30]
[19]
[20]
[21]
[22]
[23]
[24]
[25]
[26]
[27]
[28]
[29]
[30]
[31 41]
[32]
[ 33 144]
[34]
[35]
[ 36 102]
[37]
[38]
[39]
[40]
[41]
[42 92]
[43]
[44]
[45]
[46]
[47]
[ 48 236]
[49]
[50]
[ 51 105 156]
[ 52  72 314]
[53]
[54]
[55 88]
[56]
[57 88]
[58]
[59]
[60]
[61]
[62]
[63]
[64]
[65]
[ 66 186 395 396 397 461 655]
[67 99]
[68]
[69]
[70]
[ 71  96 189]
[ 72  80  87 101 339 550]
[ 73 475]
[74 99]
[75]
[76]
[77]
[78]
[79]
[ 80  87 124 125 174 176 416 417 418 584 586 587 684 685 806 807]
[81]
[ 82 206]
[ 83 300 538]
[84]
[85]
[86 87]
[ 87 124 125]
[88]
[ 89 122 148 149 150 151 152]
[90]
[91]
[92]


  1%|▏         | 242/16385 [00:00<00:06, 2414.28it/s]

[93]
[94]
[ 95 120 235]
[ 96 146]
[97]
[98]
[ 99 242]
[100 257]
[101 482]
[102]
[103 136 324]
[104]
[105]
[106]
[107]
[108]
[109]
[110]
[111]
[112]
[113]
[114 181 316]
[115]
[116]
[117]
[118]
[119]
[120]
[121]
[122 148 149 150 151 152]
[123]
[124 125]
[ 125 1619]
[ 126  691 1407]
[127]
[128 258 299]
[129]
[130]
[131]
[132 454]
[133 318 384 643 644 764]
[134 153 314]
[ 135  177  220  221  222  223  245  456 1127]
[136]
[137 268]
[138 226 227 228 229 230 231]
[139]
[140]
[141]
[142]
[143]
[144]
[145]
[146]
[147 191]
[148 149 150 151 152]
[149 150 151 152 287]
[150 151 152]
[151 152]
[152]
[153]
[154 255]
[155]
[156]
[157]
[158 241 787]
[159 291 292]
[160]
[161]
[162]
[163]
[164]
[165]
[166 260]
[ 167 1023 1024 1025 1026 1230 1231 1452 1684 1685 1686 1975 1976 1977]
[168 210]
[169]
[170]
[171 530 628]
[ 172  382  543  544 1122]
[173]
[174 219 406]
[175]
[176 232 245 386 780]
[177 220 221 222 223 245 387 388 389 390]
[178 266 322]
[179 320]
[180 181]
[181]
[182]
[183]
[184]
[185]
[186 397]

  4%|▍         | 678/16385 [00:00<00:09, 1686.30it/s]

[ 457 1126]
[458]
[ 459 1124]
[ 460 1336 1339 1877]
[461]
[462]
[463]
[464]
[ 465 2589]
[ 466 1625]
[467]
[468]
[ 469 1867 1868 2204 2984 3829 3830]
[ 470 1159]
[ 471 1376 1870]
[472]
[473]
[474]
[475]
[476]
[477]
[478 788 789]
[479 550]
[480]
[481]
[ 482  942 1157]
[483]
[ 484  679 1172]
[485 486]
[486]
[487 803]
[ 488 1624]
[ 489  972 1182 4316]
[ 490  590 2628]
[ 491 1192]
[492 977]
[ 493 2278]
[ 494  823  989 3023]
[495]
[ 496  700 3495]
[497]
[498]
[499]
[500]
[ 501  502 1008 1009]
[ 502 1010]
[503 504 708]
[504 708]
[505]
[506]
[507]
[508]
[509]
[510]
[ 511 1697]
[512]
[ 513 1047 1054 4548]
[514]
[ 515 1266]
[ 516  733  734 1271 2047 3229 3659]
[ 517 2050]
[518]
[519 744 870]
[ 520  820  871  983 1112 1117 3049]
[521 522]
[522 618]
[ 523 1076 1289]
[524 858]
[525]
[526 619 881]
[527 528 529 744]
[528 529 744]
[529 744]
[ 530  753 1784]
[ 531 1093 1530 2103 2107 2487 3726]
[532 897]
[533 534]
[534]
[ 535 2303 4190]
[ 536  740 1298 1549 2872 3277 4458]
[537]
[ 538 1323]
[539]
[540]

  5%|▌         | 851/16385 [00:00<00:10, 1479.34it/s]

[ 738 1751]
[ 739 1502 2080]
[ 740 1298 1774 2093 2475 2873 3277]
[741]
[ 742 1516]
[743]
[744]
[745 749 888]
[746]
[ 747 4650]
[748]
[ 749 1527]
[750]
[751]
[752]
[753]
[ 754  755 2900]
[ 755 1544]
[756]
[757]
[ 758 1548 2506]
[ 759 2137]
[ 760 1327 1823 2150]
[ 761 2538 2937]
[762]
[763]
[ 764 1566]
[ 765  913 1995 2158 2550 4245 4246]
[ 766  917 1565]
[767]
[768]
[769]
[770]
[771]
[772]
[ 773 1137 1855 2168 2173 2555 2954 2982 3360 3817 4256 4732 5255]
[ 774 1141 1371 4750]
[775]
[776]
[ 777 1574]
[ 778 1142 1144]
[ 779 1358 1579 1583]
[ 780 1146 1584 1585 1588 1612 1880 2185 2223 2585]
[781]
[ 782 2191]
[783]
[784]
[785]
[786 867]
[787]
[788 789]
[789]
[790]
[791]
[ 792 2219]
[ 793 1167 2221]
[794]
[795]
[ 796 1391]
[ 797  958 1170 1607 1608]
[ 798  918 1365 1894 1895]
[ 799 1181]
[ 800 1170 1173 1620 1883]
[ 801 1621 2567 2603 4321]
[ 802  961 1176 1622 1888]
[803]
[ 804 1398 1889]
[ 805 1398 1889]
[806]
[807]
[808]
[ 809  821 1406 2246 2772]
[ 810 2635 3435]
[ 811 1409]
[812]
[81

  7%|▋         | 1141/16385 [00:00<00:12, 1269.31it/s]

[ 978 3030]
[ 979 1906 3035 3881]
[980]
[ 981 1912]
[982]
[ 983 1117 1413 1636 1639 1760 2074 2851 3049]
[ 984 1638 2081]
[ 985 1641 1642 3471]
[ 986 1643 2279 2280]
[987]
[988]
[ 989 1646]
[ 990 1239 3489]
[ 991 2677]
[992]
[ 993  998 1007]
[ 994 1933 3086]
[995]
[996]
[ 997 1013]
[998]
[999]
[1000 1428]
[1001 1002 1432 2706]
[1002 1432 1949]
[1003 2710]
[1004 8117]
[1005 1669]
[1006]
[1007]
[1008 1010]
[1009 2336]
[1010]
[1011 1916 1962]
[1012]
[1013]
[1014 2527 5196]
[1015]
[1016 2347]
[1017]
[1018 1967]
[1019 2733 2734]
[1020 1021 1229 1450 2353]
[1021 1229 1450 2353 2357]
[1022 2355]
[1023 1231]
[1024 4009]
[1025 1452 1684 1685 1975]
[1026]
[1027]
[1028 3562]
[1029]
[1030 2373 4034 4992]
[1031 1696 1991 2374 2375 2376 2379 2380 2757 2760 2761 2762 3162 3165
 3576 3579 4035 4037 4498 4500 5011 5507 5508 5509 5517 6058 6059 6061
 6065 6067 6586 6589 6590 6591 6592 7114 7116 7119 7657 7662 7663 7664
 7665 7666 8189 8190 8191 8740 9291]
[1032 1238]
[1033 1699]
[1034]
[1035]
[1036 1518

  8%|▊         | 1270/16385 [00:00<00:12, 1209.97it/s]

[1196 1915 2765 3952 3953 3954 3955 4062 4066 4368 4418 4896 5906 7508]
[1197 1198 1919]
[1198 1415]
[1199 1922 2662 2663 4389 4390 4391]
[1200 2274]
[1201 1653 3076 3077]
[1202 3697]
[1203]
[1204]
[1205]
[1206 3503 4431 5414 5415 5961 5962 5963 6983]
[1207 1208 1285]
[1208 1241 3505]
[1209]
[1210]
[1211 1949]
[1212 1955 2709 3069 3939 3981 5984]
[1213 1214 1952 2712]
[1214 1952 2712]
[1215 1216]
[1216]
[1217 2328 2718]
[1218]
[1219 1958]
[1220 1226]
[1221 2345 3520 3521 3522]
[1222]
[1223 1918]
[1224 1444]
[1225]
[1226]
[1227 2341]
[1228 3989]
[1229 1450 1971]
[1230]
[1231 1976 1977]
[1232 1942 3098 4433]
[1233 1693 2051]
[1234]
[1235 1236 4492]
[1236 2751 3566 4493 4994 4995 4996 4997 5491 5492]
[1237 1989 2752 3158]
[1238]
[1239 3167]
[1240]
[1241 1284 1285 3270 4166]
[1242 1462 1704 5935 6461]
[1243 3959 4900 4902 6473]
[1244 4064]
[1245 1914 2854 2855]
[1246 2392]
[1247]
[1248]
[1249]
[1250 2010]
[1251]
[1252 1468]
[1253 1254 1472 2410 3195]
[1254 1473]
[1255]
[1256 1257 2017 2018

  8%|▊         | 1392/16385 [00:01<00:12, 1161.40it/s]

[1380 1567 1568 2209 2565 5299]
[1381 2211]
[1382 2212]
[1383 1598 1875 2213 2214]
[1384]
[1385]
[1386 2215 2216 2217 2589 2590 2988 3389 3390 3834 4304 4774 5820]
[1387]
[1388 3394]
[1389]
[1390]
[1391 3840]
[1392]
[1393]
[1394 1893]
[1395 3006 4799 4800 4801 6847 7977]
[1396 1397 2603]
[1397 2603]
[1398 1889]
[1399 1893]
[1400 3415]
[1401]
[1402]
[1403 3421 3422 4328]
[1404 2239]
[1405]
[1406 2245 3867 3868 3869 4341 4817 5865]
[1407 5324]
[1408 3437 3876]


  9%|▉         | 1509/16385 [00:01<00:13, 1120.28it/s]

[1409 3438 3930 4865]
[1410 3439]
[1411 2639 3877 3878]
[1412 2641 2642 3441]
[1413 1636 3903]
[1414]
[1415]
[1416 3919 5908 5909 6981]
[1417]
[1418]
[1419]
[1420 2685 3492]
[1421 2298 2299 4422 5398]
[1422 2010 2686 4402]
[1423 2687]
[1424 2303]
[1425]
[1426 2308 2694]
[1427 2314 6483]
[1428]
[1429]
[1430]
[1431]
[1432]
[ 1433  1666  1949  2705  2707  4927  4928  4930  7015  7016  7576  8115
  9199  9201  9715  9718  9719 10726 10731 11205 11208 11210 11212 12029]
[1434]
[1435]
[1436 2318]
[1437]
[1438]
[1439 1678 2331 2719 2728 5437]
[1440 1441 1674]
[1441 1442]
[1442]
[1443 1918 1965 1966 2717]
[1444]
[1445 2334 3124]
[1446]
[1447]
[1448 4001 7040]
[1449 2736]
[1450 2353]
[1451 2747]
[1452 2359]
[1453 1687 1688]
[1454]
[1455]
[1456]
[1457]
[1458]
[1459]
[1460]
[1461]
[1462 2291 2384 2462 2673 2674 2770 3273 5924 5934]
[1463 2277 6921 7503]
[1464]
[1465 2686 3463 5134]
[1466 2400]
[1467 1709 2011 2402]
[1468 2403 2404]
[1469 2405 3192]
[1470]
[1471 1724 2828 4084 4085]
[1472 1473 241

 11%|█         | 1730/16385 [00:01<00:13, 1076.36it/s]

[1618]
[1619 2979 4291 4324 4767 4791 5301]
[1620 4739]
[1621]
[1622 7432]
[1623 3860]
[1624 2181 2197 2199 4286 4765]
[1625]
[1626 3373]
[1627]
[1628 4796]
[1629]
[1630 6385]
[1631 2625]
[1632 2248]
[1633 4348]
[1634 2251]
[1635 3449 8018]
[1636 2276 2320 3049 3051 3117 3903 3907 4450 4854 5129 5666 5896 6205
 6272 6423 6424 6735]
[1637]
[1638 2081]
[1639 2276]
[1640]
[1641 1997 3058 6276 6776]
[1642 3058 4385]
[1643 2656 3057 3467 3468 5176]
[1644 1920 3468]
[1645 1646]
[1646]
[1647]
[1648 2766 3931]
[1649 3936]
[1650]
[1651 2289]
[1652]
[1653]
[1654 1930]
[1655 1656 1932 2295 2296 3085]
[1656 1932 2295 2296]
[1657 2684 3900 4046]
[1658 2297 5397 7538 8080]
[1659 3519 4380]
[1660 1936 3960 4642]
[1661]
[1662]
[1663 2369 3552]
[1664 8094]
[1665 3973 4925]
[1666]
[1667 3068 4439]
[1668 2321 2322 3517]
[1669]
[1670 2714]
[1671 2508]
[1672]
[1673 2509 3048]
[1674]
[1675 2722]
[1676 3125 3126]
[1677]
[1678 2344 2345 3131 3535 4460 4461 4462 4951 4952]
[1679]
[1680]
[1681]
[1682 2356 3141 

 12%|█▏        | 1944/16385 [00:01<00:13, 1049.43it/s]

[1826]
[1827]
[1828 3785]
[1829]
[1830 5767]
[1831]
[1832 1833 2152 2153 2537 4229]
[1833 2153]
[1834 2548 4241]
[ 1835  4509  4510  5014 10334]
[1836 2942]
[1837 3795 4243 4254 4720 5244 6826 8471]
[1838 2949]
[1839 1840 2554 2556 2565 3348 3798 4257 5797 5799]
[1840 2169 2554 5798 6321]
[1841]
[1842 2558 2955]
[1843]
[1844 2176 4734 5259 5268 6833 6834]
[1845 6835]
[1846 1847 3815 5274]
[1847]
[1848 2179]
[1849]
[1850 2192 2578 2958 2972 3358 4264 4265 4266 6837]
[1851 3808 5797]
[1852 2572 4271 4272 4737 5263]
[1853 2946 2976 3395 3808 4275]
[1854 2568 5270 7956]
[1855 2168]
[1856 2967 3367 4276]
[1857 3368 4278 4284 5275 5805 5830 6344]
[1858 2576]
[1859 2621 2974]
[1860 2195]
[1861 3819]
[1862]
[1863 2206 6859 7974 7975 9586 9591]
[1864 1866]
[1865]
[1866]
[1867 1868 2204]
[1868 2204]
[1869]
[1870 2207]
[1871]
[1872 2594 2955 2995]
[1873 3850 4732 4763]
[1874 2213]
[1875]
[1876]
[1877]
[1878]
[1879]
[1880 2585 4784 5817 6343 6855]
[1881]
[1882 2227]
[1883 3019]
[1884 2999]
[1885 3

 13%|█▎        | 2153/16385 [00:01<00:13, 1035.43it/s]

[2030 2794 3206 3207 3632]
[2031 2413 2414]
[2032]
[2033 7722 7723]
[2034]
[2035]
[2036]
[2037 5582 5594 8802]
[2038 3215 3218 3687 5596 5648]
[2039]
[2040 2041]
[2041 6144]
[2042 3220 3221 3648 4107 5071]
[2043]
[2044 4577]
[2045]
[2046]
[2047]
[2048]
[2049 2439 2816 2818 4123 5089 5090 5616 5617 6167 7232 7791 8871]
[2050 5090]
[2051 2346 2818 4123 5618]
[2052 4131]
[2053]
[2054 4139 4595 5105 5631 6710 7246 7809]
[2055 2056 3238]
[2056 3238]
[2057 4599]
[2058 4592]
[2059]
[2060 3681]
[2061]
[2062 5111]
[2063]
[2064]
[2065 4625]
[2066 5121]
[2067]
[2068 2849 5131]
[2069]
[2070]
[2071 7283]
[2072]
[2073]
[2074]
[2075]
[2076]
[2077]
[2078 2465]
[2079 4636]
[2080 6073]
[2081]
[2082]
[2083 3278 3279]
[2084 2098 2870 6755]
[2085]
[2086 2087]
[2087 3714]
[2088]
[2089]
[2090 2091 2872]
[2091 2872]
[2092]
[2093 2475 2873 3277 3715 4663 6762]
[2094]
[2095]
[2096]
[2097 5699]
[2098 2870 5694 6754 6755]
[2099]
[2100 3284]
[2101 3742 5705 6258]
[2102 2103 2107 2486 2891 3289]
[2103 2886 3722 372

 14%|█▍        | 2360/16385 [00:01<00:13, 1022.38it/s]

[2234 3854]
[2235]
[2236 2611 3825 4790]
[2237]
[2238 3017]
[2239 2618]
[2240 3019]
[2241 2613 3383]
[2242 4805]
[2243 2621 4330 5851 5852 6378 6379 7443]
[2244 3022 4809 4813]
[2245 3867 3868 3869]
[2246]
[2247 2628]
[2248]
[2249 3433]
[2250 3435 5325 7999]
[2251 2636 3439]
[2252]
[2253 2254 3880 5873]
[2254]
[2255]
[2256 2644]
[2257 4835]
[2258 3040 3041 3446 9099]
[2259 2260 2646 2647]
[2260 2646 2647 3894 4364 5328]
[2261]
[2262]
[2263]
[2264]
[2265]
[2266 3054 5358]
[2267 3046 3601]
[2268]
[2269 2650 3452 3453 4381]
[2270]
[2271]
[2272]
[2273]
[2274 3459]
[2275 5357]
[2276 2320 7855]
[2277 3464 3554 3912]
[2278]
[2279 3467 3469]
[2280 3469 4864 5362 5363]
[2281]
[2282]
[2283]
[2284 5371 7524]
[ 2285  3172  4063 11151]
[2286 2768]
[2287 5894 6605]
[2288]
[2289 2677]
[2290]
[2291]
[2292 2680]
[2293 3877 4416]
[2294]
[2295 2296]
[2296]
[2297]
[2298 2299 4422 5398]
[2299 3493 5398]
[2300 2301 2387 3087 3560 6960]
[2301 2617 3259 3486]
[2302 3091]
[2303]
[2304 8088]
[2305 2774 3500 406

 16%|█▌        | 2565/16385 [00:02<00:13, 1014.70it/s]

[2438]
[2439]
[2440 2441 2819 3661 4124 5091 5619]
[2441]
[2442]
[2443 3654]
[2444 3679 5635 7814 8902]
[2445 5106 5107 5117]
[2446 6713]
[2447 6718]
[2448 5637]
[2449]
[2450]
[2451]
[2452 3213]
[2453]
[2454]
[2455 3686 5650 6722]
[2456 2810 6671 6724]
[2457 3252]
[2458]
[2459 2845 2846 6207]
[2460 2673 2863 3273 3599 4171 4630 4853 5535 5934 6216 6217 6736]
[2461]
[2462 2674]
[2463 3268]
[2464 6214 6223]
[2465 4618]
[2466]
[2467]
[2468 2517 5141 5683 6232]
[2469 2470]
[2470]
[2471]
[2472 2870]
[2473 3714]
[2474]
[2475 2873 3277 3715 6241]
[2476 3716]
[2477]
[2478 2879]
[2479]
[2480]
[2481]
[2482 2483 3286 3720 3721 4176 4652]
[2483]
[2484]
[2485 2886 3288 3723 3724 3725 4655]
[2486 3289]
[2487 4654]
[2488]
[2489]
[2490 3292 3734 3735]
[2491 4176 5147 7864]
[2492 3739]
[2493]
[2494 4458]
[2495 3743]
[2496]
[2497]
[2498 2899 3746 3747 5162]
[2499 4666 5709 6261 6262]
[2500 3305]
[2501]
[2502]
[2503 2880 5164 6240]
[2504 3310]
[2505 2903 3311]
[2506 3500]
[2507 5713 5718]
[2508 3050 3051

 17%|█▋        | 2767/16385 [00:02<00:13, 989.76it/s] 

[2637]
[2638]
[2639 2670]
[2640 3880]
[2641 2642 3034 3441]
[2642 3034 3441 4821 5873]
[2643]
[2644 6893]
[2645]
[2646 3044 4349 4841 5339 9093]
[2647]
[2648]
[2649]
[2650 3899 5891]
[2651 5892]
[2652]
[2653 8036]
[2654 4913 5420]
[2655 3464 6230]
[2656]
[2657 4386]
[2658 2659 3061 5139 5140 5417 7534]
[2659 3498]
[2660 4388 5368 6930 8098 8590 9673]
[2661]
[2662 2663 4389 4390]
[2663 4389 4390]
[2664 3060 3923 4390]
[2665 2666 3536]
[2666 3536]
[2667]
[2668]
[2669]
[2670 3061 3476 3927]
[2671]
[2672]
[ 2673  2770  4171  5133  5924  8202 13158]
[2674 5923 6620 7285]
[2675]
[2676 3072 3083 3084]
[2677]
[2678 3092 3584 3585 4516 4887 4888 4908 5017 5384 6606]
[2679]
[2680 3081]
[ 2681 13296 13637 14433]
[2682 5390]
[2683 6452]
[2684 6743 7284 8375]
[ 2685  3492 14061]
[2686 3463 8060]
[2687 4426 5942 5943 7146 8613]
[2688 4955]
[2689]
[ 2690  3958  6026 13794]
[2691]
[2692]
[2693]
[2694 3501]
[2695]
[2696]
[2697 3104]
[2698 3707 4463 4863 5029 5387 5529 6476 7499]
[2699 3494]
[2700 6492 

 18%|█▊        | 2966/16385 [00:02<00:13, 990.27it/s]

[2834]
[2835]
[2836 3685]
[2837 3685]
[2838]
[2839 4610 7256]
[2840 3247 3684 4148]
[2841 3245 3685]
[2842 4617 5655 6200]
[2843 2844 3254 3688]
[2844 3688]
[2845 2846 6207]
[2846 5664 9454]
[2847]
[2848]
[2849]
[2850]
[2851]
[2852 2854 3260]
[2853 2855 3261 4860]
[2854 3260 5137 6219]
[2855 3074 3261 4632 5675]
[2856]
[2857 3262]
[2858]
[2859 3263 3264 3702 6231]
[2860 3705 5901 5914 5927 6519 6935 9121 9167]
[2861]
[2862 2864]
[2863]
[2864 6228]
[2865]
[2866 3706 4641 9467]
[2867 3905 6224 7693 8939]
[2868]
[2869]
[2870 4175 5694 6754]
[2871]
[2872 3277 4645]
[2873 3277 3715]
[2874]
[2875 5145 5691]
[2876 2877]
[2877 2878]
[2878]
[2879]
[2880 3278 3279 3280 6240]
[2881 2882 3307]
[2882 3307]
[2883]
[2884 2885 5146]
[2885]
[2886 3726]
[2887]
[2888]
[2889 3292]
[2890 3736 3737]
[2891 3296 5151]
[2892 4182]
[2893]
[2894]
[2895]
[2896]
[2897]
[2898]
[2899 3746 3747]
[2900 6764]
[2901 5153 6758 7310 7867 8954]
[2902]
[2903]
[2904 4375 4676 5181 5713 7321]
[2905 5124 5166 6767]
[2906]
[290

 19%|█▉        | 3167/16385 [00:02<00:13, 992.20it/s]

[3034 4821 5873]
[3035]
[3036 8006]
[ 3037  3884  4353  4829  5334  5877  5878  6404  6405  6899  8013  8552
  8554  9098  9635 10136 10140 10641]
[3038 4833 4834]
[3039 5338 5881]
[3040 3041 4362 5886]
[3041 4362]
[3042]
[3043 3451]
[3044 3440 5328 5872]
[3045]
[3046 3899 5346]
[3047]
[3048 3050 4851]
[3049 3903 3907 4854 5896 6423 6424]
[3050]
[3051 3117 4450 6272]
[3052 4379]
[3053]
[3054 5358 9316]
[3055]
[3056]
[3057 3058 4385]
[3058 4385]
[3059 3921 4860 5018]
[3060 4390]
[3061 3476 3927]
[3062 6029]
[3063 3593 5373 5377 9692 9727]
[ 3064  3478  3932 10177]
[3065]
[3066 5024]
[ 3067  7526 10181]
[3068 3938 4439 6445 7000 7528]
[3069]
[3070 3490 4881 5392]
[3071 4404 4405 4407]
[3072 3083 3084]
[3073 4517 8063]
[3074 5928 6952 7080 7683]
[3075]
[3076 3077]
[3077]
[3078]
[3079 3486 4402]
[3080 3945 3946 4411]
[3081]
[3082]
[3083 3084]
[3084 6457]
[3085]
[3086 3492]
[3087 3259 3859 4327 6960]
[3088]
[3089 3090]
[3090]
[3091]
[3092]
[3093 3266 4165]
[3094]
[3095 3934 6941 7019 7499]


 21%|██        | 3368/16385 [00:02<00:13, 992.32it/s]

[3234 3671]
[ 3235  5104  7806 11351]
[3236 7813]
[3237 6710]
[3238]
[3239]
[ 3240 11947]
[3241]
[3242]
[3243]
[3244 4546 8346 9353]
[3245 4573 5643]
[3246 3247]
[3247 3684 4148]
[3248]
[3249]
[3250 4613]
[3251 7819 7820 9448]
[3252 4615]
[3253 3254 7273]
[3254 4623 4624 5123 5660]
[3255 4159]
[3256]
[3257]
[3258]
[3259 4402 8373]
[3260 3261 5743]
[3261 4519 4861 5751 8769]
[3262]
[3263 3264 3702 6231 9337]
[3264 3265 3702 6231 7291]
[3265]
[3266 3913 4058 4165 4863 5028 5366 5676]
[3267]
[3268]
[3269]
[3270 4167 4168 5898 6229 6230 7542 8222 8380]
[3271]
[3272]
[3273 4630 4853 5934]
[3274 3612]
[3275]
[3276 3711]
[3277 3715 4645 4663 6238 6760]
[3278 3279 3280 7302]
[3279 5154 6240 6751 6753 7301 7303 8947 9479 9485 9998]
[3280 6242]
[3281 3282 5695]
[3282]
[3283 3298 3745]
[3284]
[3285 4653]
[3286 3721]
[3287 3295]
[3288 3723 3724 3725 4655]
[3289]
[3290]
[3291 3731]
[3292]
[3293 3739]
[3294 4660 5701]
[3295 5151]
[3296 5151]
[3297 5152 6757 7309 7865 7866 8388 8950]
[3298 3745]
[329

 22%|██▏       | 3568/16385 [00:03<00:12, 992.90it/s]

[3434]
[3435 5318 6884 7999]
[3436]
[3437]
[3438 4348]
[3439]
[3440 4351 4387]
[3441]
[3442]
[3443 4828]
[3444]
[3445]
[3446 4839 6900]
[3447 3893 3894 4364]
[3448]
[3449 7481]
[3450]
[3451]
[ 3452  3453  4372  5893  8932 10977]
[3453 3899 8228 9764]
[3454 3455]
[3455 5347]
[ 3456  3694  4376  4856  6419  6420  6421  6422  7497  8568 10149]
[3457 3952 4417 6919]
[3458 4377]
[3459]
[3460 6456]
[3461]
[3462]
[3463]
[3464]
[3465 4378]
[3466 6428]
[3467 3468]
[3468]
[3469 4864 5362 5363]
[3470]
[3471]
[3472]
[3473]
[3474 5370]
[3475 3878 5915]
[3476 3927]
[3477]
[3478]
[3479]
[3480]
[3481]
[3482 3484 4409]
[3483 3484]
[3484 4406 4409]
[ 3485 11153]
[ 3486 11154]
[3487]
[3488 4011 4057]
[3489 3914 3948 4414 4893 5026]
[3490 4881 5392]
[3491 3931]
[3492]
[3493 6459]
[3494 4897]
[3495]
[3496]
[3497]
[3498 5950]
[3499 6468 6928 8089]
[3500 6482 9845]
[3501 6462]
[3502]
[3503 4431 5415 5961 5962 5963 6486]
[3504 3964]
[3505 6491]
[3506 3967]
[3507 3508 3509 3969]
[3508 4440]
[3509 5424]
[3510]


 23%|██▎       | 3770/16385 [00:03<00:12, 993.84it/s]

[ 3633  4562 14675]
[3634]
[ 3635  7176  8256  8257  9355 10382 10383]
[3636]
[3637 8264 9870]
[3638 6649 7727]
[3639 4097 9366]
[3640 3641 5579 5593 6666 9379]
[3641 5593 7734]
[3642]
[3643 4564 5644 8810]
[3644 3645 5063 5585 7258]
[3645 5585]
[ 3646  8277 10896]
[3647]
[3648 6145 8814]
[3649]
[ 3650  6165  6680  8313 10902]
[3651 3652 4114 4115 5078 6674 6675]
[3652 3653 4114 4115 5078 5603 6675]
[3653 4115 7209 9389]
[3654]
[3655 5605]
[3656 8852]
[3657]
[3658]
[3659]
[3660 6167]
[3661 4124]
[3662 7234 7793 8873 8874 9929]
[3663]
[3664 5077]
[3665]
[3666 3667 4580]
[3667 5084]
[3668]
[3669 4132]
[3670 4133 4134 5100 6176]
[3671]
[3672]
[3673]
[3674 3675]
[3675 4597 5637]
[3676]
[3677 4592]
[3678]
[ 3679  7815  8339 13017]
[3680 8331]
[3681 4090]
[3682 3685]
[3683 5555 6107]
[3684 4148]
[3685]
[3686]
[3687]
[3688]
[3689]
[3690]
[3691 5670]
[3692]
[3693 7280 8374]
[3694 4376]
[3695]
[3696 3953]
[3697 4170 5141]
[3698]
[3699 4701 5204 5209 5752 8436 8983 9521 9528]
[3700]
[3701 3980 4

 24%|██▍       | 3971/16385 [00:03<00:12, 994.72it/s]

[3834 4304]
[3835]
[3836]
[3837]
[3838]
[3839]
[3840 5292]
[3841]
[3842]
[3843]
[3844]
[3845]
[3846 4313]
[3847]
[3848]
[3849]
[3850 5838]
[3851 3852 4321 4788]
[3852 4321 5300]
[3853]
[3854]
[3855 4793 5843]
[3856]
[ 3857  3858 10578]
[3858]
[3859 4327]
[3860]
[3861]
[3862 4329]
[3863 4329]
[3864]
[3865]
[3866]
[3867 3868 3869 4341 4817 5865]
[3868 3869 4341 4817 5865]
[3869 4341 4817 5865]
[ 3870  3871  4343  4344  5867  6395  6883 12154]
[3871 4343 5320 5321 5867 6395 6396 6883 7997 8519]
[3872 8004]
[3873]
[3874]
[3875]
[3876]
[3877 3878]
[3878]
[3879 9076]
[3880 5873]
[3881]
[3882]
[ 3883  4827 10635]
[ 3884  4828  4829  5334  5877  5878  6404  6405  6899  8539  9095  9635
 10134 10135 10136 10138 10139 10640]
[3885]
[3886 3887]
[3887 3888 4359 5338]
[3888 4359]
[3889]
[3890]
[3891]
[ 3892  4353  4838  7475  9094 10133]
[3893]
[3894 3895]
[3895]
[3896 6406 6879 7446]
[3897]
[3898 9643]
[3899]
[3900 3901 4046 8594]
[3901 4047 5685]
[3902]
[ 3903  4854  5896  7494 10150]
[3904]
[390

 25%|██▌       | 4171/16385 [00:03<00:12, 994.59it/s]

[4036 7660 9293]
[ 4037  4500  6058  7661 12916]
[ 4038  5518  7658  9811 11732 12924 13598]
[4039 6064 6588]
[4040 5010 6035 6066 6068 7118]
[4041 4042 5510 6587]
[4042 4503]
[4043]
[4044]
[4045]
[4046 4047]
[4047 5685]
[4048 7125]
[4049]
[4050]
[4051 4518]
[4052 6077 6078 9313]
[4053 8204 9314]
[4054]
[4055 4907]
[4056 4489]
[4057 8772]
[4058 5028 6225]
[4059 5030 6090]
[4060 5030]
[4061 4529 5031]
[4062 7129 9843]
[4063]
[ 4064  6224  6460  8608  9144 10661 11586 12385]
[4065]
[4066 4368 6096 8227]
[4067]
[ 4068  6088  8219  8629  9333 12960]
[4069]
[4070 4071]
[4071]
[4072 6100]
[4073 4535 5545 7702]
[4074 5038]
[4075]
[4076 4539]
[4077]
[4078]
[4079]
[4080 4081]
[4081]
[4082]
[ 4083 10866 12968 13016 13018 13306 13930 13931]
[4084 4085 5053 8908]
[ 4085  4149  4607  5053  8907  8908  8911  8912 10948 10950 10951]
[4086 6714 8337 8342 9886]
[4087 6630]
[4088 6112 7166 8793]
[4089 6114]
[4090]
[4091 4092 4093 6120]
[4092 4093 6120]
[4093 6120]
[4094]
[4095]
[4096 5557]
[4097]
[4098]

 27%|██▋       | 4372/16385 [00:04<00:12, 997.18it/s]

[4237 4238 4239 4716 5235 5236 5237 5238 5777]
[4238 4239 4716 4717 5235 5236 5237 5238 5779 5782 6308 6311]
[ 4239  4716  5235  5236  5237  5238  5777  5781  5782  6307  6820  7376
  8458 11039]
[4240]
[4241 4719 6823]
[4242]
[4243 4720 5244 6826 7386]
[4244]
[4245]
[4246]
[4247]
[4248 4249 5790 5796]
[4249 5790]
[ 4250 13435]
[4251 5250]
[4252]
[4253 8473]
[4254 4512]
[4255 4725]
[ 4256  4732  4754  6839  7409 10084 10085 10598 10601 10602 11068 11069
 13749]
[4257 5797]
[4258]
[4259]
[4260]
[4261 5262]
[4262 7406]
[4263 4738]
[ 4264  4265  6837  7407  7952  9578 10083]
[ 4265  6837  7407  7952  7953  9028 10083]
[4266]
[4267 4744]
[4268 4729]
[4269 7954]
[ 4270  5802  7402  7406  7957 11529 11942 12729]
[4271 4272]
[4272]
[4273 4747 7408]
[4274 4743 4798 5253 7401]
[4275 4750]
[4276]
[4277]
[4278 4284]
[ 4279  4297  5805  5830  6343 10607]
[ 4280  6844  9581 11067]
[4281]
[4282]
[4283 4287 4755 5280]
[4284 5275]
[4285]
[4286 4765 5808 7964]
[4287 4755 5280]
[4288 5282 8490]
[4289]
[

 28%|██▊       | 4572/16385 [00:04<00:11, 990.91it/s]

[4439 7000]
[4440 4920]
[4441]
[4442 5500 6574]
[4443]
[4444 4445 4926 7012]
[4445 4926 7013]
[4446]
[ 4447  5430 10222 13190]
[4448 4937]
[4449]
[4450]
[4451 4939]
[4452]
[4453 4941 8120 8648]
[4454 5988 7579]
[4455]
[ 4456 14369]
[4457]
[4458]
[4459 5444]
[4460 4951 4952]
[4461 4462]
[4462]
[4463 8126 9213]
[ 4464  7652  7825  8663  8690  8706  9219  9776 12082 12251]
[4465 6524]
[4466]
[4467 5002]
[4468]
[4469 8144]
[4470]
[4471]
[4472]
[4473]
[4474 7061]
[ 4475  9260 12474]
[4476]
[ 4477  9749 11241]
[4478]
[ 4479  7042  7607  9732  9738  9795 10761 12478]
[4480 4978 9752]
[4481]
[4482 6236 8066]
[4483]
[4484]
[4485 7559 8159]
[4486 6727 7593 7606 7819 8682]
[4487 5484 6032 6033]
[ 4488 12084]
[4489 6003]
[4490]
[4491]
[4492]
[4493 4995 4996 4997 5492 7092 9784]
[4494 7098 7642 8728 9279 9791]
[ 4495  9280  9281 10301]
[4496]
[4497 7083]
[4498 4503 5508]
[ 4499  5008  9292 11301 14397]
[4500]
[ 4501  6594  7120  8746  9804 11729 11730]
[4502]
[4503]
[4504 5005]
[4505]
[4506]
[4507 

 29%|██▉       | 4774/16385 [00:04<00:11, 999.05it/s]

[4637 4638 9461]
[4638 8769]
[4639]
[ 4640 10983]
[4641 9467]
[4642 5033]
[4643 6237 8941]
[4644 5689 7152 7299 7858 8384]
[4645 6238 7859 7860]
[4646]
[4647 5145 9999]
[4648]
[ 4649  8949 10990]
[4650]
[4651 6246]
[4652]
[4653 6246]
[4654]
[4655]
[4656 4657]
[4657]
[4658]
[4659]
[4660]
[4661]
[4662]
[4663 5154 7310]
[4664]
[4665 5710 6262]
[4666 5160 5709]
[4667]
[4668]
[4669]
[4670 5351 9491]
[4671 5727]
[ 4672  5717  6772  7320  8959 10511 11472 11473 13397]
[ 4673  9700 10033]
[4674]
[4675]
[4676 5713 6768 6788]
[4677]
[4678]
[4679]
[4680]
[4681]
[4682 6288 8412]
[4683]
[4684]
[4685 4688 5180 5734]
[ 4686  4687  5179  5732  8424 10029 10031 10032 10536 11013 11014 11486
 11488 12288]
[ 4687  5732  6792  8424  8974  8975 11014]
[4688 5180 5734]
[4689]
[4690 4691 5736 6291]
[4691 5736 6291]
[4692]
[ 4693  5749  7359  7916  8979 10041]
[4694 5185]
[4695 5191]
[4696]
[4697]
[ 4698 10550]
[4699]
[4700 5135 5203 6739]
[4701]
[4702]
[4703]
[4704 5211 5758]
[4705]
[4706 4707]
[4707]
[4708 

 30%|███       | 4977/16385 [00:04<00:11, 1002.14it/s]

[4839 6900]
[4840]
[4841]
[4842]
[4843]
[4844]
[4845]
[4846 5343 5344 5531 6416 7133 8028]
[4847]
[ 4848 10648]
[4849]
[4850]
[4851]
[4852]
[4853]
[4854 5896 6423 7494]
[4855]
[4856 6419 6420 6421 6422 6913 7497]
[4857]
[4858 8616]
[4859 5902]
[4860 4861 6980 7552 9337]
[4861 4867 5136 5751 6484 6980 7552 8087 8090 8608 9113 9168 9761]
[4862]
[ 4863  5018  5675  5917  6745  6986  7547  7844  7852  8051  8052  8096
  8099  8130  8133  8207  9114  9459  9679 10161 10701 10702]
[4864 5362 5363]
[4865 5018]
[4866 4867 7128]
[4867]
[4868 4895 5040 6929]
[4869 4870 6932]
[4870]
[ 4871  4872  7517  8048  8049  9665 10168 10660 10662]
[ 4872  6936  7517  8048  8049  9665 10168 10660 10662]
[4873]
[4874]
[ 4875  8591  9130  9676 10176]
[4876]
[4877 4878 4879 6441]
[4878 4879]
[4879]
[4880]
[4881 8075]
[4882]
[ 4883  5380  6446  6447  7530 10678]
[4884 5380]
[4885 6475 6477]
[ 4886  6449  6450  6956  7540  8067  8070  8081  9138 10681 11160]
[4887 4888 4908 5017 5383 5384 5385]
[4888 4908 5383 5

 32%|███▏      | 5181/16385 [00:04<00:11, 1007.51it/s]

[5041]
[5042 6627]
[5043 5551]
[5044]
[5045]
[5046]
[5047]
[5048]
[5049]
[5050 7165 8240 8248]
[5051 6709 8333]
[5052]
[5053]
[5054 5560]
[5055 5114]
[ 5056  9861 10381 10874 10876]
[5057]
[5058]
[5059 5573 6655]
[ 5060  5067  7727  9443 11783]
[ 5061  5072 10395 10891]
[5062 5585 7258]
[5063 5064 9445]
[5064]
[ 5065  5645  6633  7738  7739  7740  9879 10396 10397 10398 10865 10892
 10957 11371 11786 11787]
[5066 9377]
[ 5067  6135  8812 10896]
[5068]
[5069 6139]
[5070]
[5071]
[5072 5556]
[ 5073  7817 11800]
[5074]
[5075 5077 5600]
[5076 7751]
[5077 8826]
[5078 5603 6675]
[ 5079  7757 10420]
[5080]
[ 5081  9392 13763]
[5082 5606 7775 7776 8305]
[5083 5607 6158 9908]
[5084]
[5085]
[5086 5087 6693]
[5087 6693]
[5088 6693 7231]
[5089 5616]
[5090 7232]
[5091]
[5092 5620]
[5093 6169]
[5094 7234]
[ 5095  7234  7793  7794  8316  8876  8877  9413 11415]
[5096 7226 7799 9930]
[5097]
[ 5098 11834]
[5099]
[5100 6176]
[5101]
[ 5102  9938 11836 11837]
[5103]
[ 5104  7806  9425 10461 11351]
[5105]
[

 33%|███▎      | 5385/16385 [00:05<00:10, 1010.46it/s]

[5246]
[5247]
[5248 7939]
[ 5249  9563 11052 13438 13439 14024]
[5250]
[5251]
[5252 6868]
[5253]
[5254]
[5255]
[5256]
[5257 5819 5823 5838]
[5258 6325]
[5259 6833 6834]
[5260]
[5261]
[5262]
[5263 9026 9577]
[5264 5265]
[5265]
[5266 6330 9034 9036]
[5267]
[5268 6837]
[5269 5802 6322 6323 7410 7958]
[ 5270  7399 11945]
[5271 5803 6334]
[5272]
[5273]
[5274]
[5275]
[5276]
[5277 6845]
[5278]
[5279]
[5280 6338]
[5281]
[5282 6339 8490 9584]
[ 5283  9583 10088 11081]
[5284]
[5285]
[5286 5818]
[5287]
[ 5288 11534]
[5289]
[5290 5818 9041]
[5291 6853 6854]
[5292]
[5293 5827 6358]
[5294]
[5295 5296]
[5296]
[5297]
[5298 6857]
[ 5299 11077]
[5300 5839]
[5301]
[5302 5841 6860]
[5303 8506]
[5304]
[5305]
[5306 5307]
[5307]
[5308]
[5309 5843 6377 7962 7985 9605]
[5310 6367]
[5311 5853 6873]
[ 5312  5313  6874  8510 10618]
[5313 6875]
[5314 8510]
[5315]
[5316]
[5317]
[ 5318  7447 10107]
[5319 5862 5863 8514]
[5320 5341 7452 8518]
[5321 5341 7454]
[5322]
[5323]
[5324]
[5325]
[5326 6398]
[5327]
[5328 5872]

 34%|███▍      | 5590/16385 [00:05<00:10, 1016.13it/s]

[5452]
[5453 6001]
[ 5454  6524  9734 10241 12049]
[5455 6004]
[ 5456 12469]
[5457]
[5458 6006 6007 7045 8670]
[5459 7597]
[5460]
[5461 6227 7598 8765]
[5462 6196 7598 7599]
[5463 5464 5465]
[5464 5465 6536 8145]
[5465 6538]
[5466]
[5467 6536 7602]
[5468 6542]
[5469]
[5470]
[5471 6015 6017 6018 6552 7074]
[5472]
[5473]
[5474]
[5475 5476]
[5476]
[5477]
[5478 5937 6456]
[5479 6023]
[5480]
[5481 5965 9127]
[5482 7590 7624]
[ 5483  7084  7627 10246 10275 11660]
[5484 6032]
[5485]
[5486]
[ 5487 10287]
[5488]
[ 5489  6035 13883 14150 15201 15328]
[5490]
[5491 6038]
[5492 7092]
[ 5493  5494  6042  6044 13252]
[5494 6042 6044]
[ 5495  5496  6043 10797]
[ 5496  6043  8724  9787 12095 12901]
[5497]
[5498]
[5499]
[5500 6574]
[5501]
[ 5502  5777  5778  5779  5783  6308  6311  6576  7107  7373  7934  8456
  8462 11506]
[5503 6030]
[5504 8153 8689 9236]
[ 5505  5511 12528 13596]
[5506 6057 6585]
[ 5507  5517  6058  6059  6065  6589  6592  7116  7657 15331]
[5508 5509 6067 6590 7114]
[ 5509  5510  60

 35%|███▌      | 5796/16385 [00:05<00:10, 1020.26it/s]

[5658 7271 7272 8365]
[5659]
[5660]
[5661 5663 6203]
[5662 5663 6203]
[5663]
[ 5664  8369  9454 10487]
[5665]
[5666 6735]
[5667 6211]
[5668 6211 7836]
[5669 7838]
[5670 5671]
[5671]
[ 5672 10490]
[5673]
[5674]
[5675 5679 5917 6741 6986 7844 8133 8575 8930 8931 9175 9176 9330 9679
 9680]
[5676 6215]
[ 5677  7137  9830 10495 10845]
[5678 6218 6740 9976]
[ 5679  9330 10497]
[5680]
[ 5681  5951 10204 11156]
[5682 6228]
[5683 6232]
[5684]
[5685]
[5686]
[5687]
[ 5688 11763]
[5689 7152 7299 8386]
[5690]
[5691]
[5692]
[5693]
[5694 6754 6755]
[5695]
[5696]
[5697]
[5698]
[5699 7306 7863]
[5700 7864]
[5701]
[5702 6254]
[5703]
[5704 6256]
[5705 6258]
[ 5706 10004 11471]
[5707 6259]
[5708]
[5709 6261]
[5710 6262]
[5711 6263]
[5712 6263]
[5713 5718 6767 6768 6788]
[5714 6769]
[5715 7882 9489]
[5716 5721 6270]
[ 5717  6271 10996]
[5718]
[5719 7886 9494]
[5720 7329]
[5721 6270 7330 8404]
[5722]
[ 5723  7341  7901  9502 10020 10021 11010 11886]
[5724 6932]
[5725]
[5726 6285 9726]
[5727]
[5728]
[5729 67

 37%|███▋      | 6004/16385 [00:05<00:10, 1027.17it/s]

[5867 6395 6883 7997]
[5868]
[ 5869  8527  9614 10116 11101]
[5870 6887]
[5871 7999]
[5872 6411]
[5873]
[ 5874  9083  9621 10119 11961]
[5875]
[5876]
[5877 6404 8539 9095]
[5878 8539]
[5879 5880 8540]
[5880 8541]
[ 5881  9632 10129]
[5882]
[5883 7472]
[5884]
[5885 6902 7473 8012]
[5886 6900 8554]
[5887 8557]
[ 5888 11700]
[5889]
[5890]
[5891 6910]
[5892 6911]
[5893]
[5894]
[5895 6267 6768]
[ 5896  6423  6424  8372 10150]
[ 5897  6426 12761]
[5898 7500]
[5899 5900]
[5900]
[ 5901  6519  9109 12766]
[5902 6477 8615]
[5903 5951 6925]
[5904]
[5905]
[5906 7508]
[5907]
[5908 5909 6981]
[5909]
[5910]
[5911 8582]
[5912 6433]
[ 5913  6935  6987  7080  7152  7516  8575  9166  9252  9458 13501 13520]
[ 5914  6933  6935  8586  9167  9664 11140]
[5915]
[5916]
[ 5917  5918  6988  9704 12563]
[5918 6940]
[ 5919 11123 11588 12388 12777 13152 14545]
[5920]
[5921]
[5922]
[5923 6620]
[5924 6461 9153]
[5925 8061]
[5926 5984]
[5927 8600 9678]
[5928 6952 7299]
[ 5929  8071 11593 12000]
[5930 6451]
[5931 6957

 38%|███▊      | 6213/16385 [00:05<00:09, 1033.81it/s]

[6074 8759]
[6075]
[ 6076 12951 13912 14190]
[6077 6078 9313]
[6078 9313]
[6079]
[6080 6081 7681]
[6081]
[6082]
[6083 7134]
[6084 7135]
[ 6085  8213  9325  9699 11455]
[6086 9728]
[6087 7139 7689 7690 7691 8770 9838]
[ 6088  7140  8219  8629  9333 10350]
[6089 6603 8758 8774]
[6090]
[6091 6463]
[6092]
[6093 7535]
[6094 7696]
[ 6095 10856 11756]
[6096]
[6097]
[6098 7154 7701 8231]
[6099]
[6100 8233]
[6101]
[ 6102  7156  7157  8784 10364]
[6103]
[ 6104  7161  9347 10366]
[6105 6563 7162]
[6106]
[6107 6656]
[6108 6109]
[6109]
[6110 6111]
[6111]
[ 6112  7166  8793 11348 11770 12971]
[6113 6114 6638 8246]
[6114 7167 8246]
[ 6115  6187  8249  8343 10374 13307]
[6116]
[6117]
[ 6118 10869 12645]
[6119]
[6120]
[6121]
[6122]
[6123]
[6124 6646]
[6125]
[6126 6648 8797]
[6127 6128 6633 6649]
[6128]
[6129 6651]
[6130 6653 8263 8808]
[6131 7257]
[6132]
[6133]
[6134]
[ 6135  6661 10896 10898]
[ 6136 11374 11376 11377]
[6137 6668 7193 8276]
[6138 6654 7734 9370]
[6139 6140]
[6140]
[6141]
[6142 6143 719

 39%|███▉      | 6427/16385 [00:06<00:09, 1051.03it/s]

[6287]
[6288 8412]
[6289 7349]
[6290 7911]
[6291]
[6292 7356]
[6293 6816 7358]
[6294]
[6295]
[6296]
[6297 7917 8981]
[6298]
[ 6299  9526 11023]
[6300]
[6301]
[6302 7928]
[6303 8442]
[ 6304  6814 10551]
[6305]
[6306]
[ 6307  6308  6310  6311  7373  7374  7934  8455  8456  8459  9001  9540
  9541  9543  9545  9548 10058 10059 10564 10565 10566 10567 10568 10569
 11039 11915 12302 12701]
[ 6308  6311  7373  7374  7934  8455  8456  9543  9545 10058 10564 10566]
[ 6309  7935 10059 12305]
[ 6310  8455 10059]
[ 6311  7373  7374  7934  8455  8456  8459  8462  9001  9540  9541  9543
 10058 10564 10565 10566 10567 10568 10569 11039 13416]
[6312]
[6313]
[6314]
[ 6315 10240 10574 11527 12249 13033 13617 13725 14585]
[6316]
[6317]
[6318]
[ 6319 11933]
[ 6320  8478  9006  9571  9573 11938 12708 13084]
[6321]
[ 6322  6323  9022 10599 11529 13103]
[6323 7402]
[6324]
[6325]
[6326 9024]
[6327 7403]
[6328 6329 7404 9025 9575 9576]
[6329 7404 9025]
[ 6330 11070]
[6331]
[ 6332  9028 12730]
[6333 7400 8486]

 41%|████      | 6644/16385 [00:06<00:09, 1065.54it/s]

[6503]
[6504 7577]
[6505]
[6506]
[6507]
[6508]
[6509]
[6510]
[6511]
[6512]
[6513]
[6514]
[6515]
[ 6516  7583 10233]
[6517]
[6518]
[ 6519  9730  9731 12042]
[6520 8129]
[6521]
[6522]
[ 6523  7042  8155  8163 11257 11258 13235 13555]
[ 6524  7819  9734 10241 12048]
[ 6525  7041 10244]
[6526 7594 7595]
[6527 6528 7594]
[6528 7594]
[ 6529 12052]
[6530]
[6531]
[ 6532 10753]
[6533 8141]
[6534 9740]
[6535]
[ 6536  7602  8143  8146  8676 12055]
[6537]
[6538 7603]
[ 6539  6553  7605  8357  8358  9773 10818 11725]
[6540 7060]
[6541]
[6542]
[6543]
[6544]
[6545]
[6546]
[6547]
[6548 7614 9750]
[ 6549 10767]
[ 6550  8695 10772 11269 11698 12482 12483 12484 13243]
[ 6551  7618  8157  8158  8694  9247  9262  9753 10775 10777 11677 11679
 12063 12067 12069 12486 12488 12862 13229 13230 13563 13839 13840 13841
 14115]
[6552 7073]
[6553 8357]
[6554]
[6555]
[6556]
[ 6557  7623 10788]
[6558]
[6559]
[6560]
[6561 6562 9778]
[ 6562  9223 14125]
[6563 7162]
[6564]
[6565]
[ 6566  7634  7635 11703 12885]
[6567 7

 42%|████▏     | 6864/16385 [00:06<00:08, 1083.34it/s]

[6722]
[ 6723  7244  7254 10475 13327 13328]
[6724]
[ 6725  9452  9774  9775 10745 10959 11441 13238]
[ 6726  8353  8707  8920 11443 12910 13381 13382 13983 14699]
[6727 7819 9448]
[ 6728  8673 14476]
[6729 7053]
[ 6730  7051 10482 10967]
[6731]
[ 6732  7828 10969]
[6733 8369 8926]
[6734]
[6735]
[6736 8202]
[6737]
[ 6738  6740  9975 10492 11019 12256]
[ 6739  6741 10496]
[ 6740 12257]
[6741 8930 9335]
[6742]
[6743]
[ 6744  7297  8051  8052  9467 10235 11574]
[ 6745  7496  8130  9459 10701 10702]
[6746]
[6747 7847 9840]
[ 6748 10504]
[ 6749 10503 11865]
[6750]
[6751 6753 7301 8946 9479 9998]
[6752]
[6753 7303]
[6754]
[6755]
[6756 7307]
[6757 8388]
[6758 7310 7867 8951 9480]
[6759]
[ 6760  8954  9486 13393]
[ 6761 10992]
[6762]
[6763 8392 8956]
[6764 7313]
[6765]
[6766]
[ 6767  6768  7316  8394  8395  8426 10993 12271]
[6768 6788]
[6769]
[6770]
[6771 7321]
[ 6772  7880  8960 10513]
[6773 8963]
[ 6774  7883  7884 10516]
[6775 7884]
[6776]
[6777 8403]
[6778]
[6779]
[6780 8405]
[ 6781  7332

 43%|████▎     | 7084/16385 [00:06<00:08, 1084.07it/s]

[6941]
[6942]
[6943 7031]
[ 6944  6945 13503]
[ 6945  8058 13503]
[6946]
[6947 7526]
[6948 8595]
[6949 7529 8596 9759 9760]
[6950 6951 8433 9530]
[6951]
[ 6952  8575 12792]
[6953]
[6954 9137]
[ 6955  6956  7540  8067  8611  8612  9147 10683 12001 12399]
[6956 7540 8067 8069 9681]
[6957]
[6958]
[6959]
[6960]
[6961]
[6962 9684 9685]
[6963]
[6964]
[6965 8609 8610]
[6966]
[6967]
[6968]
[6969 6970 6971 7545]
[ 6970  6971  7545 11167]
[6971 7545 8931]
[ 6972  7548 10692]
[6973]
[6974 6975]
[6975]
[ 6976  8622  8623  9154 11171]
[6977]
[6978 6979 8090]
[6979 8090]
[6980 7552 9337]
[6981]
[ 6982  6984 10269]
[6983 9696]
[ 6984  8094 12077]
[6985 8097]
[ 6986  8133  8575  8931  9109  9175  9176  9214  9680 10679 11179 11188
 11190 11571 11591 11592 11645 12003 12258 12372 12393 12426 12768 12781
 12795 13504]
[ 6987  7080  7545  8575 10180 10713 12012 12018]
[ 6988  8627  9704 11174 12020 12795 12808 12809 13993]
[6989]
[6990]
[6991 6992 7561 8631 9705]
[6992 8631]
[6993 7560]
[6994]
[ 6995  91

 45%|████▍     | 7308/16385 [00:06<00:08, 1099.48it/s]

[7163 7707 8787]
[7164]
[ 7165  8240 11432 11842 13674]
[7166]
[7167]
[7168]
[7169]
[7170]
[ 7171 10379 11777]
[ 7172  9354 10874 12576]
[ 7173  7174  9356 10384]
[ 7174 13021]
[7175]
[ 7176  8257 11361]
[7177]
[ 7178  8804  9444 10877 11360 11845 12589]
[ 7179  8259  9868 10385]
[ 7180 10888 11792]
[ 7181  8813 10472]
[7182]
[7183 7185 7741 8271]
[7184 7185 7742 8806 8811]
[7185 7741 9883]
[7186 8349]
[ 7187  8800  9368  9442 11372]
[ 7188  7745 10895 13321]
[7189]
[7190]
[7191 7192 7746 7747 8811 9883]
[7192 8275]
[7193 7261 8276]
[ 7194 12185 13323 14445]
[7195]
[ 7196 10891]
[ 7197 12186]
[ 7198  7749 11795]
[7199]
[7200]
[7201 8816 8817]
[ 7202  7203  8824  8825 11805]
[ 7203  8824  8825 11805]
[ 7204  7206  7207  7752  8284 10415]
[ 7205  8849 10417]
[ 7206  7207  7752  8284 10415 10418]
[ 7207  7752  8284 10415 10416]
[7208]
[7209]
[7210 8290 9892 9895]
[7211 7755]
[ 7212  7776  9900 10907 10908 12606]
[7213 8297]
[ 7214  7769  7770  8300  8301 11395]
[7215 7216 8302]
[7216 8302

 46%|████▌     | 7539/16385 [00:07<00:07, 1127.39it/s]

[ 7389 13454 13722 14027 14279 14495 14729 15260 15261 15400]
[ 7390 13080]
[7391]
[ 7392  7945 11063 11527]
[ 7393  8475 10592]
[7394]
[ 7395  9019 10593]
[ 7396 12724]
[7397]
[7398 9021]
[7399]
[7400]
[7401]
[7402 7406]
[7403]
[ 7404 11530 13749]
[7405]
[ 7406 11064]
[ 7407  7952  9028 10083]
[7408]
[7409]
[7410 7957 9580]
[ 7411 10086 11532]
[7412 7961]
[7413]
[7414]
[7415]
[7416]
[7417]
[7418]
[7419]
[7420]
[7421 7968]
[7422]
[7423]
[7424]
[7425]
[7426 8499]
[7427]
[7428]
[7429]
[ 7430  8503 11536]
[ 7431  9051 10098]
[7432]
[7433]
[ 7434 10614]
[7435]
[7436]
[7437 9056]
[7438]
[ 7439 12346]
[7440 7980]
[7441 7982 7983]
[7442]
[7443]
[ 7444  9064 12346]
[7445]
[7446]
[7447]
[ 7448  9069  9070 10108 11088]
[7449]
[7450]
[7451]
[7452 7453]
[7453 7454]
[7454]
[7455]
[ 7456 11098]
[7457]
[7458 9077]
[7459]
[ 7460 10122]
[ 7461  7462 10126 11089]
[ 7462 10126]
[7463 7464 8541]
[7464 8540 8541]
[ 7465 10127]
[7466 8543]
[7467 8009]
[7468]
[7469]
[ 7470  7471  8008  8542  8548  8549  9627

 48%|████▊     | 7783/16385 [00:07<00:07, 1175.81it/s]

[ 7627 10276 11660 12080 13827]
[ 7628  9237 10759]
[7629 8164 9777]
[7630]
[7631]
[7632 9264]
[ 7633 11702]
[ 7634  7635  9782 11274 11276]
[7635 8170 9265 9266]
[7636 8170 8721 9267]
[7637 8171]
[ 7638 10290 12510 14127]
[7639 8178 9281 9790]
[ 7640  7641  8178  9278  9790 10298 10801 11280]
[ 7641  8178  9278 10298 11714 13257]
[ 7642 13259 14612]
[7643]
[ 7644 10807]
[ 7645  8182  8732 10806]
[7646]
[7647]
[7648 8138 9286]
[ 7649 11228 11653]
[ 7650 10309]
[7651]
[7652 8663 9219]
[7653 8185 9798]
[7654]
[ 7655  8154 10256 11295]
[7656]
[ 7657  7662 12527 14154 14398 15572]
[ 7658 13270 14831 15821]
[7659]
[7660]
[ 7661 12116 13597]
[7662 7663 7664 7666 8189 8190 8191 9291]
[7663 7664 7666 8189 8190 8191 9291]
[ 7664  7665  7666  8189  8190  8191  9291 11299 11303 12527 12529]
[7665]
[7666 8189 8190 8191]
[7667]
[7668]
[ 7669  8193 13090 13737 14506]
[7670 8468 9300]
[7671 8196 9300]
[ 7672 11749 14178 14179 14866 15676]
[7673 8755]
[7674 8197]
[7675 9308]
[7676]
[ 7677  7685  8201 

 49%|████▉     | 8035/16385 [00:07<00:06, 1219.94it/s]

[7875]
[7876]
[ 7877  8396 10998 12677]
[7878 7879]
[ 7879 10011]
[ 7880  8960 10513 12276]
[7881]
[ 7882 10995]
[ 7883  7884  8962 10013]
[ 7884  8401  8962 10013]
[7885]
[7886 9494]
[7887]
[ 7888 12680]
[ 7889 10520]
[ 7890 10521 10522 10523 13401 13704]
[7891]
[ 7892 10524 11578]
[7893 7894 9499 9513]
[ 7894 10525]
[7895 7896]
[ 7896 10527]
[ 7897 10520]
[7898]
[7899 8965 9500]
[ 7900 10535 13062]
[7901]
[ 7902  8427  8428  9505 10035]
[ 7903 14927]
[7904]
[7905]
[7906]
[7907 8422]
[7908]
[7909 8427 8428]
[7910]
[7911]
[7912 7913 9515]
[7913]
[ 7914  8429  9516 10037 10042 11017 11901 11902]
[ 7915  8978 10546 11499 11904]
[7916]
[7917 8981]
[7918]
[ 7919  8437 12689]
[ 7920 11018]
[ 7921  7923  9525 10040 10047 10547 11022 12295 12691]
[7922]
[ 7923  9525 10040 10047]
[7924]
[ 7925 10557]
[ 7926 13709]
[7927]
[7928]
[7929]
[7930 8992]
[ 7931 12696]
[ 7932  9533 10056 11038 11505]
[7933]
[ 7934  8459  8462  9545 10566 10569]
[7935 9544]
[ 7936  8457 11914]
[7937]
[7938 8460 8461]
[7

 51%|█████     | 8298/16385 [00:07<00:06, 1268.79it/s]

[8134]
[8135]
[8136]
[ 8137 10787 11230 11231 12464 12465 13823 13824]
[ 8138  8662  9284  9286 11653]
[8139 8668 9224]
[ 8140  9736 10247]
[ 8141 11235]
[ 8142  8680 11692]
[8143]
[8144]
[ 8145  8677 12056 12846]
[8146 8676]
[8147]
[8148 9234]
[ 8149 12475]
[8150 8684 8712]
[ 8151  8685  9242 10260]
[8152 9241]
[8153 9236 9799]
[ 8154 10256 10817 11297 12857 13225]
[ 8155  8163 10285 11680 12062 12498 13555]
[8156]
[ 8157  9247  9262 12869]
[ 8158  8678  9230 10755]
[8159]
[8160]
[ 8161  8737  9449 13985]
[ 8162  9228  9239 11446 11692 13234 14702]
[ 8163 10778 11232 11257 11258 11661 11667 11668 12059 12473 13235 13555
 14110]
[ 8164  9777 10759]
[8165]
[ 8166  8713 10283 11267 11268]
[8167]
[8168]
[8169]
[8170 8721 9265 9267]
[8171]
[ 8172 10289]
[ 8173  8174  9785 10296 10799 12900 13254 13255 13584 14608]
[8174]
[ 8175 12094]
[8176]
[ 8177  8726 10296 10297 11279 11710 11712 12099 12100 12101 12102]
[ 8178  9277  9790 10801 13258]
[8179]
[8180]
[8181]
[ 8182 10304 10808]
[ 8183 10

 52%|█████▏    | 8564/16385 [00:07<00:06, 1296.60it/s]

[8401]
[8402]
[8403]
[8404]
[ 8405 12277]
[8406]
[ 8407 10027 12283]
[ 8408  8409  8428  9499 10526]
[ 8409 10526]
[ 8410  8966 11481]
[ 8411 11482 11884]
[8412]
[ 8413  8414 10028 12284 12287 13063]
[ 8414  8968  8972  9509 10028 10534 11484 12284 12287 12685 13058 13061
 13065 14244]
[8415 8969]
[ 8416 10023]
[8417]
[8418]
[8419]
[8420]
[8421]
[8422 8423]
[8423]
[ 8424  8974 11489 11889 11890 13707]
[ 8425 12290 13408]
[ 8426  8428  9513 10993 11015 11492 12292]
[8427 8428 8976]
[ 8428  8976  9513 11015]
[ 8429  9516 11017 11022 11901 11903]
[8430]
[8431]
[ 8432 12293]
[ 8433  9530 10039]
[8434]
[8435]
[8436]
[ 8437  8438 12689]
[ 8438 10037 12294]
[8439]
[8440]
[8441 9529]
[8442]
[8443]
[ 8444 10051]
[8445]
[ 8446 10552 12298 12692]
[8447]
[ 8448 14004]
[8449]
[8450]
[8451]
[8452 9534]
[8453]
[8454]
[ 8455  8459  9541 10058 10059 11506 11507]
[ 8456  8459  9001  9543  9548 10058 10564]
[ 8457 12302]
[8458]
[ 8459  9001  9540  9545 10565 10566 10567 10568]
[ 8460  8461 10060]
[8461]


 54%|█████▍    | 8835/16385 [00:08<00:05, 1325.36it/s]

[8669]
[8670]
[ 8671 10247 10750]
[8672]
[ 8673  9226  9739 12842]
[ 8674 10249 11662]
[8675]
[ 8676 12055]
[ 8677 12056 12846]
[ 8678  9230 10755]
[ 8679 13215]
[ 8680 10785 11691]
[ 8681 15441]
[ 8682 12850]
[8683 8686]
[8684 8712]
[8685]
[8686]
[ 8687 12858 14580 15497]
[8688]
[ 8689 12070 12525 13564 14391]
[8690]
[ 8691 10770]
[8692]
[8693]
[ 8694 10775 11677 12067]
[ 8695 10772 11698]
[8696]
[ 8697 12071]
[8698]
[8699 9251]
[8700]
[ 8701 10264]
[ 8702 10197 10198 10199 10268 11128 11989]
[8703]
[8704 8705]
[8705]
[8706]
[ 8707  8920 11442 12653 13982 14476 14477 14478 14698 15244 15496 15599
 15767 15850 15912]
[ 8708  9223 11259 11664]
[ 8709 11695 12496 12878]
[ 8710  9779 10281 10306 11266 12468 12879 12881 13558 13850]
[ 8711 11696 13242 13570 14103 14357 14360 14376 14578 14582 14596 14597
 14815]
[8712]
[ 8713 10283 11268]
[8714]
[ 8715 11701 12500]
[ 8716 10286]
[ 8717 10286]
[8718]
[8719]
[8720]
[8721 9267 9783]
[8722 9268]
[8723]
[8724 9787]
[8725 9276]
[ 8726  8727  978

 56%|█████▌    | 9111/16385 [00:08<00:05, 1351.44it/s]

[8944]
[ 8945  8946 10509]
[ 8946 10000 10002 10509]
[8947 9479 9998]
[8948]
[ 8949 10990]
[8950]
[8951]
[8952]
[ 8953  9482 10003]
[ 8954  9485 13393 14926]
[8955]
[8956]
[8957]
[8958]
[ 8959 10511 13397]
[ 8960 10513]
[ 8961 10514 11880 11881 13702]
[8962]
[8963]
[ 8964 11006]
[8965]
[8966]
[8967]
[ 8968  9509 11484 12284 12685 13058 13060 13061 13065 13404 13405 13406
 14244]
[ 8969 10540 11485]
[8970]
[8971]
[ 8972  9509 10028 11484 12685 13065]
[8973]
[ 8974  8975  9512 10030 11489 11889]
[ 8975  9512 10030 11487 11490]
[ 8976  9513 11015]
[8977 9514]
[8978]
[8979]
[8980]
[8981]
[8982]
[8983 9521]
[8984]
[ 8985  8986 10549]
[ 8986 10549]
[ 8987 10557]
[ 8988 11028]
[8989 9527]
[ 8990 12693]
[ 8991 13412]
[8992]
[8993]
[8994]
[8995]
[ 8996 11502]
[8997]
[8998]
[8999 9536]
[9000]
[ 9001  9540  9541  9548 10564 10565]
[ 9002 10057]
[9003 9542 9544]
[ 9004  9546 10057]
[9005 9549]
[9006]
[ 9007 11042]
[9008]
[ 9009  9013 10070 11516]
[9010]
[ 9011 10578 14728]
[ 9012 10582]
[ 9013 105

 57%|█████▋    | 9388/16385 [00:08<00:05, 1369.02it/s]

[ 9223 10754 11659 11664]
[9224]
[ 9225 10749]
[ 9226  9739 12842]
[9227]
[ 9228 11692 13986 14702]
[9229]
[9230]
[ 9231  9232  9743 10239 10271 10786]
[ 9232  9742 14105]
[9233]
[9234]
[ 9235 14107]
[9236 9746]
[ 9237 10759]
[9238]
[ 9239 11446]
[ 9240  9748 10482]
[9241]
[9242]
[ 9243 10765 11245]
[ 9244 10760]
[9245]
[ 9246  9248  9754  9755 10774 12066]
[ 9247  9262 12485 12866]
[ 9248  9754  9755 10774 11249 11678 12065 12863 12864]
[9249]
[9250]
[9251]
[ 9252  9678 10154 10180 10783 11179 11989 12804 13135 13178 13515 14192
 14314]
[9253]
[9254]
[9255]
[ 9256 12494]
[ 9257 11261 12078 15448]
[9258]
[9259]
[ 9260 12474]
[9261]
[ 9262 12485 12487]
[9263]
[ 9264 10793 13574]
[9265]
[9266]
[9267]
[9268]
[ 9269  9784 11705 12087 12092 12093 13863]
[ 9270  9274 12510 12897 14128 14133]
[9271]
[ 9272 10798 12089 12090 12091 12096 12903 13582 13868 14824]
[9273]
[ 9274 13861 14128 14133 15316]
[ 9275 10797]
[9276 9789]
[9277]
[ 9278  9280  9790 10298 10801 11280 11714]
[9279]
[ 9280 1030

 59%|█████▉    | 9670/16385 [00:08<00:04, 1389.80it/s]

[9505 9513]
[9506]
[ 9507 10027 12283]
[9508]
[ 9509 10028 10534 11484 12284 12287 12685 13058 13060 13061 13065 13404
 13405 13406 13407 14244]
[9510 9511]
[ 9511 11012]
[ 9512 10030 11487 11489 11490]
[ 9513 10034]
[ 9514 12688]
[9515]
[ 9516 10042 11017 11901 11902]
[ 9517 11897 13409]
[ 9518 14002]
[9519]
[ 9520 11495]
[9521]
[9522]
[ 9523 10041 10545]
[9524]
[ 9525 10040 10047 10548 12295 13067]
[9526]
[9527]
[9528]
[9529]
[ 9530 10039]
[ 9531 12695]
[9532]
[ 9533 10056 11038]
[ 9534  9536 10054 10562 11503]
[ 9535 10054 10055 10562]
[ 9536 10054 10562]
[ 9537 11504]
[ 9538 11504]
[9539]
[ 9540 10565 10566 10568 11039 11506]
[ 9541 10566 10568 11039]
[9542]
[ 9543 10058 10564]
[9544]
[ 9545 10566 10569]
[ 9546 12302]
[9547]
[ 9548 10564 12302]
[9549]
[ 9550 12702 14721]
[9551]
[ 9552 12703 12704 12930 14165]
[ 9553  9554 10067 10069]
[ 9554 10069]
[9555 9557]
[9556]
[9557]
[9558]
[ 9559 11519]
[ 9560 10581]
[ 9561 10075 11050]
[ 9562 13435 15404]
[ 9563 11052 13439]
[ 9564 13080 1

 61%|██████    | 9956/16385 [00:08<00:04, 1411.09it/s]

[ 9790 10298 10801 11280 12518]
[9791]
[9792]
[ 9793 12103 12906]
[9794]
[9795]
[ 9796 10311]
[ 9797  9799 10248 10312 10752]
[ 9798 10313]
[ 9799 12860 14393]
[ 9800 10815]
[9801]
[ 9802 15039]
[ 9803 13267]
[ 9804 11729 11730]
[9805]
[ 9806 12917 13597 13600 14154 14398 14624 14839 15047 15335 15467]
[9807]
[ 9808 14156]
[9809]
[ 9810 10822 11735]
[ 9811 12924]
[ 9812 11739]
[9813]
[ 9814 10825 11051 13735 13736]
[ 9815 10331 12121]
[ 9816 14938 15119]
[9817]
[9818]
[ 9819 15214]
[9820]
[9821]
[ 9822 10341]
[ 9823 10840 11753 12139 12952]
[ 9824 10841 10847 11755]
[ 9825  9978  9979 11331 11595 11596 12795]
[ 9826  9985 11120]
[ 9827 12142 14428]
[ 9828 12556]
[ 9829 10343 10344 10346 10353 10354 10843 10844 11757 11758 11979 12949
 14924]
[ 9830 10845]
[9831]
[9832]
[9833 9837]
[9834]
[ 9835 10848 11328]
[ 9836 10715]
[9837]
[9838]
[9839]
[ 9840 10852 11457]
[9841]
[ 9842 11333 11861]
[ 9843 13638]
[ 9844 10856 12562]
[9845]
[ 9846 13640 14436 15360]
[9847]
[9848]
[ 9849 14439]
[ 98

 63%|██████▎   | 10245/16385 [00:09<00:04, 1428.53it/s]

[10082]
[10083]
[10084 10085 11531]
[10085]
[10086]
[10087]
[10088 11081 12342]
[10089]
[10090 13110 13464]
[10091 13755]
[10092]
[10093 11081 12342 14034]
[10094 10095]
[10095]
[10096 10097 13759]
[10097 13759]
[10098]
[10099]
[10100]
[10101 10102 15278]
[10102]
[10103]
[10104]
[10105]
[10106 11543 11544 13476]
[10107]
[10108 11088]
[10109]
[10110 10622 13120 13121 13483]
[10111 11092]
[10112 11547]
[10113]
[10114 11100]
[10115]
[10116 12356 13126]
[10117]
[10118 10119 11961]
[10119]
[10120 10632 10633 11106 11107 11554 11963 12359 12746 12747]
[10121 10634]
[10122]
[10123]
[10124]
[10125 11108]
[10126 11089]
[10127]
[10128]
[10129]
[10130 13490]
[10131 13490]
[10132]
[10133 11560 11966 12366 12367 13127 13128 14040]
[10134 10135 10136 10138]
[10135 10640]
[10136 10137 10138 11561]
[10137]
[10138 11561]
[10139 10640]
[10140]
[10141 12368]
[10142]
[10143]
[10144]
[10145 10146 10645]
[10146 10645]
[10147]
[10148 12758]
[10149]
[10150]
[10151]
[10152 10652 11120]
[10153]
[10154 10180 128

 64%|██████▍   | 10543/16385 [00:09<00:04, 1457.83it/s]

[10379 11777]
[10380 11359]
[10381]
[10382]
[10383 12578]
[10384 12648]
[10385]
[10386]
[10387 10882]
[10388 11366]
[10389 10885]
[10390 10888 15590]
[10391 10405]
[10392]
[10393 10473 10889 12641 12974 14916]
[10394 11369 12586 12587 12588]
[10395 13652 15078]
[10396 10398 10865 11371 11786 11787 12590 13315 13651 13657 13941 13942
 15093]
[10397 10892 12590]
[10398 10865 10957 11371 11786 11787 12590 13315]
[10399 10403]
[10400]
[10401 10402 11373 12593]
[10402 11373 12593]
[10403]
[10404]
[10405]
[10406 12594 14207]
[10407]
[10408 11375 13656]
[10409]
[10410 11379 11380 11795]
[10411]
[10412 10903 12208 12612 13659]
[10413]
[10414 12193]
[10415]
[10416]
[10417]
[10418 12195]
[10419]
[10420]
[10421]
[10422]
[10423]
[10424 10425]
[10425]
[10426 11391 11392]
[10427 11394 11419]
[10428 12609]
[10429 10910 13334 13661]
[10430 13364]
[10431]
[10432 10914]
[10433]
[10434 10439 10440 12210 12613]
[10435]
[10436 10437]
[10437]
[10438 14214]
[10439 10440 12210]
[10440 12210]
[10441 11819 1261

 66%|██████▌   | 10844/16385 [00:09<00:03, 1483.33it/s]

[10679 11179 11188 11571 11591 11592 12003 12258 12781 12795 13155 13495
 13504 13505 13787 14307 14971 15538]
[10680 12782 12795]
[10681]
[10682 11158]
[10683 12001 12399]
[10684 13790]
[10685 11163 11164 12002 12402 12403]
[10686 13790]
[10687 11165 12004 13163 14080 14324 14550 14776 14978 15144 15424 15425
 15627]
[10688 11166]
[10689 12005 12407 13164 13486]
[10690 13510]
[10691 13167]
[10692]
[10693 11169]
[10694]
[10695 13511]
[10696 10697]
[10697]
[10698 13170]
[10699 15141]
[10700]
[10701 10702 14068]
[10702 14068]
[10703 11522 12311]
[10704]
[10705 11183 12422 12423 13547]
[10706]
[10707]
[10708 10710 14072]
[10709 13800 14329 14331 14981 15290 15715]
[10710 10711 12427 14332]
[10711 12016 12017 14982]
[10712 12016 12017 14333 14556]
[10713 12018]
[10714]
[10715]
[10716]
[10717]
[10718 11619]
[10719]
[10720 11618]
[10721 13186]
[10722]
[10723 12027]
[10724]
[10725 10727 10730 11201 12437 14090]
[10726]
[10727 10730 11201 12437 13806 14090]
[10728 11204 11627 12438 12818 14783

 68%|██████▊   | 11153/16385 [00:09<00:03, 1513.92it/s]

[10985]
[10986 13047 13048 13695]
[10987]
[10988 11483]
[10989 13050 13051]
[10990]
[10991]
[10992]
[10993]
[10994]
[10995]
[10996]
[10997 12675]
[10998]
[10999 11475 12676 13997]
[11000]
[11001 13399]
[11002]
[11003 13781]
[11004 13999 14711]
[11005]
[11006]
[11007 12280]
[11008 13057]
[11009]
[11010 11886 13059]
[11011]
[11012 12687]
[11013 11014 11487 11488 12288]
[11014 11488]
[11015 11485 11492]
[11016]
[11017 11901 11902]
[11018]
[11019]
[11020]
[11021 14099]
[11022]
[11023]
[11024 11499]
[11025]
[11026]
[11027 11029 11030 12296 12297]
[11028 14716]
[11029 11030 12296 12297]
[11030 12296 12297]
[11031]
[11032]
[11033 12696]
[11034]
[11035 14007 14249 15501]
[11036]
[11037]
[11038 11505]
[11039 12302]
[11040]
[11041]
[11042]
[11043 12309]
[11044]
[11045 11929 13434]
[11046 11518 12709]
[11047 11519]
[11048]
[11049]
[11050 11927 12714]
[11051]
[11052]
[11053 11054 11055 13440]
[11054 11523]
[11055 12322]
[11056 12306]
[11057 13451]
[11058 11059]
[11059]
[11060]
[11061 11939]
[11062

 70%|███████   | 11470/16385 [00:09<00:03, 1550.85it/s]

[11301 14397]
[11302]
[11303 11728 12527 12529 13597]
[11304 11305 11733 12533]
[11305 12533]
[11306 11738 12928 12929 14635]
[11307]
[11308 15054]
[11309 11310]
[11310]
[11311]
[11312 11313 14012 14848 15055 15058]
[11313 14848]
[11314 15341]
[11315 12128 12944 12945]
[11316 11750 12129]
[11317]
[11318 14187]
[11319 11752 12138]
[11320]
[11321 13292]
[11322]
[11323 11977 14191 14539]
[11324 12137]
[11325]
[11326 11597 12958 13632]
[11327]
[11328]
[11329 12146]
[11330]
[11331 11595 11596]
[11332 11461 11595 12665]
[11333]
[11334 14193]
[11335]
[11336 11337 11340 13297 13298 13921]
[11337 11340 13296 13921]
[11338 11340 13297 13507 13914 14872]
[11339]
[11340 13297 13298 13917 13921 14874]
[11341]
[11342 12155]
[11343]
[11344 12566]
[11345]
[11346]
[11347]
[11348 11770]
[11349]
[11350 12167 12646 14885]
[11351]
[11352 12571]
[11353 11772 12598 12967 13940 14668 14883 14884 15491 15758]
[11354]
[11355 11774]
[11356 13310]
[11357 12170]
[11358]
[11359]
[11360 11364 11845 12238 12589 13679

 72%|███████▏  | 11791/16385 [00:10<00:02, 1582.21it/s]

[11621 12024 12432 14340]
[11622 12027 12435]
[11623 14561]
[11624 13534 13807 14564]
[11625 13534 14564]
[11626]
[11627 12438 13192 14782]
[11628]
[11629 11631]
[11630 12035 12441 12443 13197 13812 14093 14094 14096]
[11631]
[11632 12033 12826 13194 13198 13540 14095]
[11633]
[11634]
[11635]
[11636 11637 12449 13201 13544 13545]
[11637 13545]
[11638]
[11639 12682]
[11640 12037]
[11641]
[11642]
[11643 12457 12832 13817 14996 14997 15157 15296 15297 15298]
[11644 12459]
[11645 13204]
[11646]
[11647]
[11648]
[11649 13552]
[11650 12045 13208 13548 14570 15303]
[11651]
[11652]
[11653]
[11654]
[11655]
[11656 14573]
[11657 12060 12491 13567]
[11658]
[11659]
[11660 12080 13827]
[11661 11669 13555]
[11662]
[11663]
[11664 13558]
[11665 11666]
[11666]
[11667 11668 12473 14109 14798]
[11668 12473 14109]
[11669 12059 15168]
[11670]
[11671]
[11672 13222 13566 15029]
[11673]
[11674 11675 12853]
[11675 12853]
[11676 12061]
[11677 12488 13230 13563 13839 13840 13841]
[11678 12863 12864 13228 13562]
[1

 74%|███████▍  | 12121/16385 [00:10<00:02, 1616.28it/s]

[11952]
[11953 14035]
[11954 13470 13761]
[11955 13471 13763 14957]
[11956 13765]
[11957 12742 13477 13767 14038]
[11958]
[11959 11960 12355 13125 13487]
[11960 12355 13487]
[11961]
[11962 12745]
[11963 12359 12743 12746]
[11964]
[11965]
[11966 12366 13128 14040]
[11967]
[11968 12368]
[11969 12755]
[11970 15417 15788]
[11971]
[11972]
[11973]
[11974 14967 15284]
[11975]
[11976 12762]
[11977 13293 14538 14539]
[11978 12254]
[11979 12949]
[11980 11981]
[11981 12767]
[11982 12776]
[11983 14050]
[11984]
[11985]
[11986]
[11987 13497]
[11988]
[11989 12384]
[11990]
[11991]
[11992]
[11993 12768]
[11994 11995 12770]
[11995]
[11996]
[11997]
[11998]
[11999]
[12000]
[12001]
[12002]
[12003 12075 12258 12372 12393 12781 12795 13495 13505 13509]
[12004]
[12005 12407 13164 13486]
[12006 12408 13166 14312]
[12007]
[12008 12410]
[12009 12413]
[12010 12414 13172]
[12011 14317 15538 15714]
[12012 13141 13778 13779]
[12013]
[12014 13639]
[12015 13800 14072 14331 15715]
[12016 13522 14982]
[12017 14333 14556

 76%|███████▌  | 12446/16385 [00:10<00:02, 1618.61it/s]

[12284 12685 13058 13061 13065 13404 13405 13406 14244]
[12285]
[12286]
[12287 13064 13407]
[12288]
[12289]
[12290]
[12291 14487]
[12292]
[12293]
[12294]
[12295]
[12296 12297]
[12297]
[12298]
[12299]
[12300]
[12301 13717 14720]
[12302 12303]
[12303]
[12304 12701 13075]
[12305]
[12306]
[12307 14258]
[12308 15394 15602 15917]
[12309 12314 13442 13722 13731 14275]
[12310 15397 15858]
[12311]
[12312 13726 15260]
[12313 13425 14020]
[12314 13442 14268]
[12315]
[12316]
[12317 12325 13746 14022 14941 15700]
[12318]
[12319]
[12320]
[12321]
[12322 13440]
[12323 12712 12715 13441 14940]
[12324 14732]
[12325 13085 13449 14941 15700]
[12326 12327 12727 13748 14286 14287 14519]
[12327 12727 13101 13748 14518]
[12328 13446]
[12329 13448]
[12330]
[12331 12332 13096]
[12332 13746]
[12333 15126]
[12334 16010]
[12335 12727 13748]
[12336]
[12337]
[12338]
[12339 12340 12732]
[12340 12732 14746]
[12341 16079]
[12342]
[12343]
[12344]
[12345 14294]
[12346]
[12347 13118 13766 15617]
[12348]
[12349]
[12350 134

 77%|███████▋  | 12608/16385 [00:10<00:02, 1616.78it/s]

[12577 13313 14205]
[12578]
[12579]
[12580 12966 13374 14671]
[12581]
[12582]
[12583]
[12584]
[12585 15077 15683 16129]
[12586 12587 12588]
[12587 12588]
[12588]
[12589 13679 15223]
[12590]
[12591]
[12592]
[12593]
[12594 14207]
[12595 13680]
[12596]
[12597]
[12598 12967 13027 15364]
[12599]
[12600]
[12601]
[12602 14209 15485]
[12603]
[12604 12985]
[12605]
[12606]
[12607]


 78%|███████▊  | 12771/16385 [00:10<00:02, 1619.47it/s]

[12608]
[12609]
[12610 12988 13335]
[12611 14213]
[12612 13659]
[12613 13957]
[12614]
[12615]
[12616 13338]
[12617 12993 13338]
[12618 12994 13663]
[12619 14216]
[12620]
[12621]
[12622 12623 13342]
[12623 13342]
[12624 13344]
[12625 13345 13346 13664]
[12626]
[12627 13348]
[12628]
[12629]
[12630 14209]
[12631]
[12632 12991 13337 13964]
[12633 13006 13965]
[12634 14686]
[12635]
[12636 13670 13671]
[12637]
[12638]
[12639]
[12640 13012 13672]
[12641 12974]
[12642]
[12643]
[12644]
[12645]
[12646 13677]
[12647 13313]
[12648]
[12649]
[12650 14233]
[12651 14695]
[12652 12838 13029 14580 14809 15248 15641]
[12653 13982]
[12654]
[12655 13683 14479]
[12656 13378 14617 14697 15001 16108 16131]
[12657 14239]
[12658]
[12659]
[12660 12764]
[12661 15100]
[12662]
[12663]
[12664 13042]
[12665 15419]
[12666]
[12667 13699]
[12668 14659 15104]
[12669]
[12670 13394 13994]
[12671 13396]
[12672 13706 13997 16163]
[12673 12677 13999]
[12674]
[12675]
[12676]
[12677 14711]
[12678]
[12679]
[12680]
[12681]
[12682

 79%|███████▉  | 12933/16385 [00:10<00:02, 1617.90it/s]

[12904 14134 14388 14389]
[12905]
[12906]
[12907]
[12908]
[12909]
[12910 15943 16097]
[12911]
[12912 13033 13686 15249]
[12913 12914 14149]
[12914 14149 14830 15040]
[12915]
[12916]
[12917 13597 13600 14154 14398 14624 14839 15047 15467]
[12918]
[12919 14155 15049 15986 16055]
[12920 13882 15329]
[12921 15022 15338]
[12922 14598 15336 15900]
[12923 13605]
[12924 13598]
[12925 13273 13890]
[12926 13891]
[12927 13892 14845]
[12928 12929]
[12929 13892]
[12930 14165]
[12931 13076 14162 14255]
[12932 12933 13619 14025 14853 14854 14855]
[12933 13619 14025 14853 14854]
[12934 14858 15346]


 80%|███████▉  | 13099/16385 [00:10<00:02, 1628.16it/s]

[12935 15209]
[12936 14173]
[12937]
[12938 13094 13901 14175 14183 14408 14862]
[12939 12942 13902]
[12940]
[12941]
[12942 13902]
[12943 13288 13905 13908 14176 15675]
[12944 12945]
[12945]
[12946]
[12947]
[12948]
[12949 14924]
[12950]
[12951 12952 13912 14425 15218]
[12952 12953 13912]
[12953 13912]
[12954]
[12955]
[12956]
[12957]
[12958 13631 13632]
[12959]
[12960 14430 14553]
[12961 15480]
[12962 13169 13915 14315]
[12963]
[12964 12965 14194 14195 14196]
[12965 13641 14195 14196]
[12966 14663]
[12967 14668]
[12968 13016 13018]
[12969 13315 13368 13651 13657 13675 13935 14667 14910 15093 15363 15586
 15766 15838]
[12970 14889]
[12971 13934]
[12972 14205]
[12973]
[12974]
[12975]
[12976 13653 14676 15481]
[12977]
[12978]
[12979 13654 14207 14445]
[12980]
[12981]
[12982]
[12983 13950 14209]
[12984 14679 15235]
[12985 13349 14211]
[12986 13332]
[12987 14451 14680]
[12988 13335]
[12989]
[12990]
[12991 13337 13964 14459 14682]
[12992]
[12993 13338]
[12994 13663]
[12995 13957 14215]
[12996]

 81%|████████  | 13266/16385 [00:10<00:01, 1639.30it/s]

[13238 15018]
[13239 13849 14357 14578 14582 14595 14597 15007 15646 15732 15803 15886
 16119]
[13240 14617 15312 15493 15848 15852 15913 16108]
[13241]
[13242 13570 14103 14357 14360 14376 14578 14582 14596 14597 14815]
[13243]
[13244 13834]
[13245 14821]
[13246 14385 15455]
[13247 13862 14383 14384 14385 15455]
[13248 14131]
[13249 13580]
[13250]
[13251]
[13252 14608]
[13253]
[13254 13255]
[13255]
[13256]
[13257]
[13258 15027]
[13259]
[13260 13872]
[13261 13585]
[13262 15984 16234]
[13263]
[13264]
[13265 14827]
[13266 14619 15247]
[13267]
[13268 13882]
[13269]


 82%|████████▏ | 13435/16385 [00:11<00:01, 1654.19it/s]

[13270 13271 15199 15200]
[13271 14840 15337]
[13272]
[13273 13890 14633]
[13274 13723 14402]
[13275 13276]
[13276]
[13277]
[13278 13614 13893 14849]
[13279 14935]
[13280 13895]
[13281 13608 15340 15345 15577]
[13282]
[13283 14645 15211]
[13284 13452]
[13285 13627 13906 13907 14180 14652 15067]
[13286]
[13287 14867]
[13288 13905 13908 14176]
[13289 15677]
[13290 15070]
[13291]
[13292]
[13293 14191 14538 14870 15107]
[13294 14428]
[13295]
[13296 13637 14433 14873 14875 15358 15679]
[13297 13298 13507 14874]
[13298]
[13299 13698]
[13300]
[13301]
[13302]
[13303 14665]
[13304]
[13305 13367 14911]
[13306 13930 13931 14690]
[13307]
[13308]
[13309 15229]
[13310]
[13311 14202 14203 15227]
[13312]
[13313 14675]
[13314 14450 15846]
[13315 13651 13657 13976 14890 15093]
[13316]
[13317]
[13318 15371]
[13319 15077 15683]
[13320]
[13321]
[13322]
[13323 14688]
[13324]
[13325 14447 14448]
[13326]
[13327 13328]
[13328 13948]
[13329]
[13330]
[13331]
[13332]
[13333]
[13334 13661]
[13335]
[13336]
[13337]


 83%|████████▎ | 13603/16385 [00:11<00:01, 1659.69it/s]

[13578]
[13579]
[13580 13581]
[13581]
[13582 14824]
[13583 14387]
[13584]
[13585 14825]
[13586 13836 14590 14591 14808 15016 15459 15598 15818 15909 16023 16136]
[13587 14121]
[13588 13845 14577 14590 14616 14805 14808 14814 15010 15029 15192 15933]
[13589 14619 15247 15644 15944 16182]
[13590 14828]
[13591]
[13592 14396 15037]
[13593 14147]
[13594]
[13595]
[13596 14835]
[13597 13600 14154 14398 14624 14839 15047 15467]
[13598]
[13599]
[13600 14154 14398 14624 14839 15047 15335 15467]
[13601]
[13602]
[13603]
[13604 15201 16179]
[13605]
[13606 14630 15339 15889 15901]
[13607]
[13608 14401 15340 15344 15345 15470 15577]


 84%|████████▍ | 13774/16385 [00:11<00:01, 1674.66it/s]

[13609]
[13610 14160 15202 15204]
[13611 14254 14848]
[13612 13613]
[13613 13893 15747]
[13614 14849]
[13615 14640 15056 15057 15575 15747]
[13616 14167 14641]
[13617 13732 15396 15399 16007]
[13618 14404 15059 16044]
[13619 14025 14644 14854]
[13620 13621]
[13621 15473 15950]
[13622 13623 14182 14412 14946]
[13623 14182 14647 14648 15994]
[13624]
[13625]
[13626 14653 14867 15754 15831]
[13627 13907]
[13628]
[13629]
[13630]
[13631]
[13632]
[13633 14429]
[13634]
[13635]
[13636 14193 14431]
[13637 14432 14873 14875 15358 16060]
[13638 15137]
[13639 13692]
[13640 14436]
[13641]
[13642]
[13643 14877]
[13644 13652 15229]
[13645 14197 15238]
[13646 15595]
[13647 14231]
[13648 14440]
[13649 15588]
[13650]
[13651 13657 14890 15093]
[13652 14880 15762]
[13653 13937 14443 14676 15481]
[13654]
[13655]
[13656]
[13657 13658 14890 14910 15093 15838]
[13658]
[13659]
[13660]
[13661]
[13662]
[13663]
[13664]
[13665 13670 14898]
[13666 13670]
[13667]
[13668 14458]
[13669 14461 15087]
[13670 13671]
[13671

 85%|████████▌ | 13950/16385 [00:11<00:01, 1700.06it/s]

[13926 13976 14666 15363]
[13927 14881]
[13928 14668]
[13929 14914 15955 16107]
[13930 13931 14672 14690 14911]
[13931]
[13932]
[13933 15369]
[13934]
[13935 14910 15363 15595 15766 15838]
[13936 14670 14878 15095 15490]
[13937 14443 14676]
[13938]
[13939]
[13940]
[13941 13942]
[13942]
[13943]
[13944]
[13945]
[13946]
[13947 15241]
[13948 14231 15241]
[13949]
[13950 14210]
[13951]
[13952]
[13953]
[13954 14211]
[13955]
[13956 13957 14215 14216]
[13957 14215 14216 14681]
[13958]
[13959]


 86%|████████▌ | 14130/16385 [00:11<00:01, 1727.77it/s]

[13960]
[13961 15954]
[13962]
[13963]
[13964]
[13965]
[13966]
[13967 15378]
[13968 14224]
[13969 14897]
[13970]
[13971]
[13972 14198 14469 15842]
[13973 14470 14914 15490 15597 16107]
[13974 14472]
[13975 14470 15690]
[13976 14667 15093 15363]
[13977]
[13978]
[13979 14583 15029]
[13980]
[13981 13985 14475 15387]
[13982]
[13983 14699 15244]
[13984]
[13985 15387]
[13986 14702 15498]
[13987]
[13988 14704 14705]
[13989 14704 14705]
[13990]
[13991 14708]
[13992]
[13993]
[13994]
[13995 13996]
[13996 15252]
[13997]
[13998]
[13999 14485 14711]
[14000]
[14001]
[14002]
[14003]
[14004 15692]
[14005]
[14006]
[14007 14249 15501]
[14008]
[14009]
[14010 14251 14253 15110]
[14011 15110]
[14012 14930 15055 15058 15111]
[14013]
[14014]
[14015]
[14016]
[14017 14948]
[14018 14260 15258]
[14019]
[14020 15398]
[14021 14264 14265 14726]
[14022 14284 15401]
[14023]
[14024]
[14025 14853 14854]
[14026 15266]
[14027]
[14028 14032 14738 15267 15923]
[14029]
[14030 14280]
[14031]
[14032 14417 14738 15678 15923 159

 87%|████████▋ | 14315/16385 [00:11<00:01, 1762.29it/s]

[14295 15526]
[14296 15617]
[14297 14963 15127 15416 15618 15873 15926 15972 16048 16049]
[14298 14958 14959 15128 15619]
[14299]
[14300 14970 15622]
[14301]
[14302]
[14303]
[14304 14762 15134]
[14305]
[14306]
[14307]
[14308 14548]
[14309]
[14310 15421]
[14311]
[14312]
[14313 14314]
[14314 15288]
[14315 14872 15679]
[14316 15140]
[14317 14771]
[14318]
[14319]
[14320 14772]
[14321 14771 15714]
[14322]
[14323 14773 15422 15423]
[14324 14550 14776 14978 15144 15425 15627]
[14325 14979 14980]
[14326 14327 14770 15626]


 89%|████████▊ | 14505/16385 [00:11<00:01, 1802.90it/s]

[14327]
[14328]
[14329 14331 14981 15290 15715]
[14330]
[14331 14981 15290 15715]
[14332 14555 14775 15291]
[14333 14556]
[14334]
[14335 14980]
[14336]
[14337]
[14338 14768]
[14339 14768]
[14340 14558]
[14341]
[14342 14564]
[14343 14988]
[14344 15431]
[14345 14565]
[14346]
[14347]
[14348 15296 15297 15298]
[14349]
[14350]
[14351]
[14352 14571 14788 15000 15631 15723]
[14353]
[14354 15161 16007 16084]
[14355 15171 15310 15311 15450 15739 15877 15879 15978 16017 16085 16215]
[14356 15017]
[14357 14360 14376 14578 14582 14596 14597 14815 15645 15732]
[14358]
[14359 14475 15017 15638 15725 15726 15801]
[14360 14376 14578 14582 14596 14597 14815]
[14361]
[14362 14793 14794]
[14363]
[14364]
[14365 14619 15805]
[14366 14804 15729 15881 16085]
[14367 15014]
[14368 15174 15642]
[14369]
[14370]
[14371 15177]
[14372 15034 15911 15960]
[14373]
[14374 15245 15641]
[14375]
[14376 14578 14582 14597 14815]
[14377]
[14378]
[14379 15020 15021 15183]
[14380 14382 14601 15022 15023 15044 15315 15338 15453

 90%|████████▉ | 14702/16385 [00:11<00:00, 1852.58it/s]

[14684]
[14685 15088 15689]
[14686]
[14687 15092]
[14688 14890]
[14689]
[14690 14911 15366]
[14691]
[14692]
[14693 15592]
[14694]
[14695]
[14696 15494 16265]
[14697 15493 15961 16024 16108 16131 16195]
[14698 15244 15496 15767 15850]
[14699 15767 15960]
[14700 15001 15848 15958 16132 16161]
[14701 15962 16039 16067 16068 16162]
[14702 15498]
[14703]
[14704]
[14705]
[14706 15102]
[14707]
[14708]
[14709 14710]
[14710]
[14711]
[14712]
[14713]
[14714 14928]
[14715]
[14716]


 91%|█████████ | 14907/16385 [00:11<00:00, 1911.30it/s]

[14717 15108 15500]
[14718 14719 15254 15389 15390 15391 15693 15694 15773 15855 15963 16006]
[14719 15254 15389 15390 15391 15693 15694 15773 15855 15963 16006]
[14720]
[14721]
[14722]
[14723]
[14724 15513]
[14725 15115]
[14726 15117 15603]
[14727 15118]
[14728 15507]
[14729 15120 15261 15920]
[14730 15508]
[14731 14937]
[14732 15401 15700]
[14733 14932 15119 15782 16008 16186]
[14734 15121 16150 16168]
[14735 14942]
[14736 15511 15866]
[14737 15704]
[14738 15923]
[14739 15610]
[14740]
[14741]
[14742 15519]
[14743]
[14744 14745 15274 15413 15871]
[14745 15274 15413 15414 15871]
[14746]
[14747]
[14748 15523]
[14749 14954]
[14750 15127 15530]
[14751 15710]
[14752 14958]
[14753 15416 15620]
[14754 14755 15130 15532]
[14755 15130 15532]
[14756]
[14757]
[14758 15133]
[14759]
[14760 15790]
[14761 14972 15534]
[14762 15134]
[14763]
[14764 15789]
[14765]
[14766]
[14767]
[14768]
[14769]
[14770 15626]
[14771]
[14772]
[14773 15422 15423]
[14774]
[14775 15146]
[14776 14978 15144 15424 15425 15627

 92%|█████████▏| 15120/16385 [00:11<00:00, 1976.45it/s]

[15106]
[15107]
[15108]
[15109]
[15110 15856]
[15111]
[15112 15394]
[15113]
[15114 15396 15695]
[15115 15603]
[15116]
[15117]
[15118]
[15119 15780 15782 16008 16186]
[15120]
[15121 15776 16168]
[15122]
[15123 15512 15671 15750 16059 16113]
[15124 15519]
[15125 15271 15412 15612 16010]
[15126]
[15127 15528 15529 15972 16012 16049]
[15128]
[15129]
[15130 15532]
[15131]
[15132 15622]
[15133]
[15134]
[15135]
[15136 15624]
[15137]
[15138]
[15139]
[15140]
[15141]
[15142]


 94%|█████████▎| 15343/16385 [00:12<00:00, 2051.94it/s]

[15143]
[15144 15424 15425]
[15145]
[15146]
[15147]
[15148]
[15149 15542 15928]
[15150 15294 15717 15874]
[15151 15543]
[15152 15153 15429 15630]
[15153 15544 15630]
[15154 15544 15545]
[15155 15431]
[15156]
[15157 15298 15721]
[15158]
[15159 15635]
[15160 15433]
[15161]
[15162 15307 15934]
[15163]
[15164 15552 15636 15801]
[15165]
[15166 15558]
[15167 15313]
[15168]
[15169 15170 15555]
[15170 15555]
[15171]
[15172]
[15173]
[15174 15642]
[15175]
[15176]
[15177 15446]
[15178]
[15179]
[15180 15447]
[15181]
[15182 15194 15323 15463]
[15183]
[15184]
[15185]
[15186 16028 16120 16160]
[15187]
[15188]
[15189]
[15190]
[15191]
[15192 15438 15737 16023]
[15193 15461]
[15194 15323]
[15195 15820]
[15196 15660 15744 16027 16193]
[15197]
[15198]
[15199 15200]
[15200 15821]
[15201 15328 16179 16205]
[15202]
[15203 15778]
[15204]
[15205 15670]
[15206]
[15207]
[15208 15827]
[15209]
[15210 15349]
[15211 15351]
[15212 15673]
[15213 15579 15674]
[15214]
[15215]
[15216]
[15217]
[15218]
[15219 15835]
[15220

 95%|█████████▌| 15578/16385 [00:12<00:00, 2141.07it/s]

[15567 15945]
[15568 15657 16174]
[15569]
[15570]
[15571 15734 16087]
[15572]
[15573]
[15574]
[15575 15747]
[15576]
[15577]
[15578 15829 15830]
[15579 15674]
[15580 15994]
[15581]
[15582]
[15583]
[15584]
[15585 15952]
[15586 15595]
[15587 16258]
[15588]
[15589]
[15590]
[15591 15684 16033]
[15592]
[15593]
[15594]
[15595 15766]
[15596]
[15597 15690]
[15598 15818 15909 16023 16037 16136 16139 16198 16230]
[15599]
[15600]
[15601]
[15602 15917]
[15603]
[15604]
[15605 16043]
[15606 15607 15860 16075]
[15607 16075]
[15608]
[15609 15968]


 97%|█████████▋| 15828/16385 [00:12<00:00, 2246.98it/s]

[15610 15868]
[15611]
[15612 16010]
[15613 16046]
[15614]
[15615]
[15616]
[15617]
[15618 15873 15926 15972 16012 16048 16049]
[15619]
[15620]
[15621]
[15622]
[15623]
[15624]
[15625]
[15626 15791]
[15627]
[15628 15716]
[15629]
[15630]
[15631]
[15632]
[15633 15634]
[15634 15800]
[15635]
[15636 15724 15801]
[15637]
[15638 15640 15731]
[15639 16331]
[15640 15725 15726 15801]
[15641 15805 15849 16214]
[15642]
[15643]
[15644 16141]
[15645]
[15646]
[15647 15893]
[15648]
[15649 15813 16053]
[15650]
[15651]
[15652 15738 15808 15979]
[15653 16175]
[15654 15894 16121]
[15655]
[15656]
[15657]
[15658]
[15659]
[15660 15744]
[15661 15987]
[15662]
[15663 15822 15899]
[15664 15816 15988 16143 16144]
[15665]
[15666]
[15667 15901]
[15668]
[15669 16102]
[15670 15747]
[15671 15750 16059]
[15672]
[15673 15866]
[15674]
[15675 15753 16128]
[15676]
[15677]
[15678 15995]
[15679 15757]
[15680]
[15681 15905 16032]
[15682]
[15683 16129]
[15684 16033]
[15685]
[15686]
[15687]
[15688]
[15689]
[15690]
[15691 16065]
[1

 98%|█████████▊| 16109/16385 [00:12<00:00, 2414.40it/s]

[16102]
[16103 16104]
[16104]
[16105]
[16106 16180]
[16107]
[16108 16131]
[16109]
[16110 16210]
[16111 16340 16370]
[16112]
[16113]
[16114 16138]
[16115 16272]
[16116 16136 16216]
[16117]
[16118 16319]
[16119]
[16120 16160]
[16121]
[16122]
[16123]
[16124 16246 16257]
[16125]
[16126]
[16127 16174]
[16128]
[16129]
[16130]
[16131]
[16132]
[16133]
[16134]
[16135]
[16136 16139 16198 16216 16221 16230]
[16137 16138]
[16138]
[16139 16198 16230]
[16140]
[16141 16266]
[16142]
[16143 16144]
[16144]
[16145 16223]
[16146]
[16147]
[16148 16259]
[16149]
[16150]
[16151]
[16152]
[16153]
[16154]
[16155]
[16156]
[16157]


100%|██████████| 16385/16385 [00:12<00:00, 1320.21it/s]


[16158]
[16159]
[16160]
[16161]
[16162]
[16163 16197 16269]
[16164]
[16165]
[16166]
[16167]
[16168]
[16169]
[16170]
[16171 16301]
[16172]
[16173]
[16174]
[16175]
[16176 16307]
[16177]
[16178]
[16179 16205]
[16180]
[16181 16261]
[16182]
[16183]
[16184 16280]
[16185 16270]
[16186]
[16187 16212]
[16188]
[16189]
[16190 16191 16202 16203 16233 16245 16256 16257 16283 16284]
[16191 16202 16203 16233 16245 16256 16257 16283 16284]
[16192]
[16193]
[16194]
[16195 16368]
[16196]
[16197]
[16198 16230]
[16199]
[16200]
[16201]
[16202 16233 16245 16256 16284]
[16203 16233 16245 16284]
[16204 16223 16278]
[16205]
[16206]
[16207]
[16208]
[16209 16290 16343]
[16210]
[16211]
[16212 16243]
[16213]
[16214 16324 16378]
[16215]
[16216]
[16217]
[16218 16267]
[16219]
[16220]
[16221]
[16222 16277]
[16223]
[16224]
[16225]
[16226 16251 16289 16309 16321 16354 16356]
[16227]
[16228]
[16229]
[16230]
[16231 16272]
[16232]
[16233 16245 16246 16256 16257 16283 16284]
[16234]
[16235]
[16236 16258]
[16237]
[16238 16244

CLASSIX_T(sorting=popcount, radius=0.33, minPts=50, group_merging=tanimoto_distance, mergeScale=1.33, mergeTinyGroups=True)

In [2]:
# print(len(set(clx_m.labels)))
# print("ARI: ", ari(true_labels, clx_m.labels))
print(len(set(clx_t.labels)))
print("ARI: ", ari(true_labels, clx_t.labels))
# clx_labels = deepcopy(clx_t.labels)
# indices = np.arange(data.shape[0])
# np.random.shuffle(indices)
# print(silhouette_score(data[indices[::20]], clx_labels[indices[::20]], metric='jaccard'))
# print(silhouette_score(data[indices[::20]], true_labels[indices[::20]], metric='jaccard'))

214


NameError: name 'ari' is not defined

In [ ]:
# for i in range(len(set(clx_m.labels))):
#     print(f"Cluster {i}: ", np.sum(clx_m.labels==i))
for i in range(len(set(clx_t.labels))):
    print(f"Cluster {i}: ", np.sum(clx_t.labels==i))

In [ ]:
for i in range(len(set(true_labels))):
    print(f"Cluster {i}: ", np.sum(true_labels==i))
# for i in range(len(set(clx_t.labels))):
#     print(f"Cluster {i}: ", np.sum(clx_t.labels==i))

In [106]:
from copy import deepcopy
print(len(set(clx_t.labels)))
print("ARI: ", ari(true_labels, clx_t.labels))
s = 0
for i in range(10):
    clx_labels = deepcopy(clx_t.labels)
    indices = np.arange(data.shape[0])
    np.random.shuffle(indices)
    # data = data[indices[::10]]
    # true_labels = true_labels[indices[::10]]
    st+=silhouette_score(data[indices[::10]], true_labels[indices[::10]], metric='jaccard')
    s+=silhouette_score(data[indices[::10]], clx_labels[indices[::10]], metric='jaccard')
print(s/10)
print(st/10)

184
ARI:  0.13043280581199362


/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric ja

0.059627973088725285
173263250.08458632


In [ ]:
101
ARI:  0.01584649924321185
-0.06677582217835673

In [29]:
ari(true_labels, y[1:])


0.016839694370390967

In [88]:
ari(true_labels, db.labels_)

0.08903354398220155

In [8]:
from sklearn.cluster import DBSCAN
import time

start = time.time()
db = DBSCAN(eps=0.33, min_samples=5, metric='jaccard' ).fit(data)
end = time.time()
print("DBSCAN took", end-start, "seconds")
db_scan_time.append(end-start)
ari_score = ari(labels, db.labels_)

/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric ja

DBSCAN took 5064.842609882355 seconds


NameError: name 'db_scan_time' is not defined

In [3]:
# Run Manhattan Clustering

m_data = np.array(data, dtype=np.float32) # Need to convert data to float for Manhattan
clx_m.fit(m_data)


OWN AGGREGATION


100%|██████████| 90498/90498 [00:49<00:00, 1821.30it/s]  


  aggregation time: 49.70823526382446
  search time: 0.13016462326049805
  ips time: 49.182782888412476
  merging time: 0.57818603515625
 minPts Merging
small clusters [1 2]
CS:  [9.0493e+04 4.0000e+00 1.0000e+00]
label_sp_copy_2 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0

NameError: name 'CS' is not defined

In [6]:
clx_t.explain()

The data was clustered into 16401 groups. These were further merged into 184 clusters.


In [3]:
clx_m.minPts

50

In [72]:
from sklearn.metrics import silhouette_score

# score_data = silhouette_score(data[::100], clx_t.labels[::100], metric='jaccard')
score_data = silhouette_score(data[::100], db.labels_[::100], metric='jaccard')

/home/research/nlagroup/.local/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2317: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


In [73]:
score_data

0.05272480594421823

In [10]:
vec = np.random.rand(1024,1)
print(vec.shape)
probe = data@vec

print(len(np.unique(probe)))

(1024, 1)
51103
